
import funcsig_conversions.grib_stub_funcsig_conversions.grib_accessor_class_stub_funcsig_conv as grib_accessor_class_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_accessor_stub_funcsig_conv as grib_accessor_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_bits_any_endian_stub_funcsig_conv as grib_bits_any_endian_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_buffer_stub_funcsig_conv as grib_buffer_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_date_stub_funcsig_conv as grib_date_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_util_stub_funcsig_conv as grib_util_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_expression_stub_funcsig_conv as grib_expression_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_parse_utils_stub_funcsig_conv as grib_parse_utils_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_context_stub_funcsig_conv as grib_context_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_value_stub_funcsig_conv as grib_value_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_ieeefloat_stub_funcsig_conv as grib_ieeefloat_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_optimize_decimal_factor_stub_funcsig_conv as grib_optimize_decimal_factor_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_scaling_stub_funcsig_conv as grib_scaling_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_errors_stub_funcsig_conv as grib_errors_stub_funcsig_conv

grib_stub_funcsig_conversions = [
    grib_accessor_class_stub_funcsig_conv.grib_accessor_class_stub_funcsig_conversions,
    grib_accessor_stub_funcsig_conv.grib_accessor_stub_funcsig_conversions,
    grib_bits_any_endian_stub_funcsig_conv.grib_bits_any_endian_stub_funcsig_conversions,
    grib_buffer_stub_funcsig_conv.grib_buffer_stub_funcsig_conversions,
    grib_date_stub_funcsig_conv.grib_date_stub_funcsig_conversions,
    grib_util_stub_funcsig_conv.grib_util_stub_funcsig_conversions,
    grib_expression_stub_funcsig_conv.grib_expression_stub_funcsig_conversions,
    grib_parse_utils_stub_funcsig_conv.grib_parse_utils_stub_funcsig_conversions,
    grib_context_stub_funcsig_conv.grib_context_stub_funcsig_conversions,
    grib_value_stub_funcsig_conv.grib_value_stub_funcsig_conversions,
    grib_ieeefloat_stub_funcsig_conv.grib_ieeefloat_stub_funcsig_conversions,
    grib_optimize_decimal_factor_stub_funcsig_conv.grib_optimize_decimal_factor_stub_funcsig_conversions,
    grib_scaling_stub_funcsig_conv.grib_scaling_stub_funcsig_conversions,
    grib_errors_stub_funcsig_conv.grib_errors_stub_funcsig_conversions,
]

# Return a list of all the funcsig conversions
def all_grib_stub_funcsig_conversions():
    return grib_stub_funcsig_conversions
