import funcsig_conversions.grib_stub_funcsig_conversions.grib_accessor_class_stub_funcsig_conv as grib_accessor_class_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_accessor_stub_funcsig_conv as grib_accessor_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_bits_any_endian_stub_funcsig_conv as grib_bits_any_endian_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_bits_fast_big_endian_stub_funcsig_conv as grib_bits_fast_big_endian_stub_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.grib_expression_stub_funcsig_conv as grib_expression_stub_funcsig_conv

grib_stub_funcsig_conversions = [
    grib_accessor_class_stub_funcsig_conv.grib_accessor_class_stub_funcsig_conversions,
    grib_accessor_stub_funcsig_conv.grib_accessor_stub_funcsig_conversions,
    grib_bits_any_endian_stub_funcsig_conv.grib_bits_any_endian_stub_funcsig_conversions,
    grib_bits_fast_big_endian_stub_funcsig_conv.grib_bits_fast_big_endian_stub_funcsig_conversions,
    grib_expression_stub_funcsig_conv.grib_expression_stub_funcsig_conversions
]

# Return a list of all the funcsig conversions
def all_grib_stub_funcsig_conversions():
    return grib_stub_funcsig_conversions
