
import funcsig_conversions.grib_cpp_funcsig_conversions.all_grib_cpp_funcsig_conv as all_grib_cpp_funcsig_conv
import funcsig_conversions.grib_stub_funcsig_conversions.all_grib_stub_funcsig_conv as all_grib_stub_funcsig_conv

# Return a list of all the funcsig conversions
def all_funcsig_conversions():
    return all_grib_cpp_funcsig_conv.all_grib_cpp_funcsig_conversions() + all_grib_stub_funcsig_conv.all_grib_stub_funcsig_conversions()
