build:
  modules:
    - ecbuild
    - ninja
    - aec
    - netcdf4
  dependencies:
    - ecmwf/eckit@develop
  parallel: 64
  cmake_options:
    - -DENABLE_EXTRA_TESTS=1
    - -DENABLE_ECCODES_OMP_THREADS=1
    - -DENABLE_ECKIT_GEO=ON
    - -DENABLE_ECKIT_CODEC=ON
