repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        exclude: '^\.cd/conda/meta\.yaml$'  # conda recipe: Jinja, not YAML
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/ecmwf/ci-infrastructure
    rev: dac4b18ffe60c317fbab05246e851b6971f7eabf
    hooks:
      - id: check-ci-approval
