SET(ENABLE_EXTRA_TESTS     ON  CACHE BOOL "Enable extra tests")
SET(ENABLE_ECCODES_THREADS ON  CACHE BOOL "Enable POSIX threads")
SET(ENABLE_MEMFS           ON  CACHE BOOL "Enable MEMFS")
SET(ENABLE_JPG_LIBOPENJPEG OFF CACHE BOOL "Disable OpenJPEG")
