def patch(klass):
    klass.cannot_convert_method("init")
    klass.cannot_convert_method("unpack_long")
    klass.cannot_convert_method("pack_double")
    klass.cannot_convert_method("pack_long")
    klass.cannot_convert_method("pack_string")
    klass.cannot_convert_method("next")
    klass.cannot_convert_method("unpack")
    klass.cannot_convert_method("pack_double_array_as_long")
    klass.cannot_convert_method("unpack_string_array")
    klass.cannot_convert_method("unpack_string")
    klass.cannot_convert_method("notify_change")
    klass.cannot_convert_method("destroy")
    klass.cannot_convert_method("pack_string_array")
