
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_accessor_class_stub_funcsig_mappings as grib_accessor_class_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_accessor_stub_funcsig_mappings as grib_accessor_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_bits_any_endian_stub_funcsig_mappings as grib_bits_any_endian_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_buffer_stub_funcsig_mappings as grib_buffer_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_date_stub_funcsig_mappings as grib_date_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_util_stub_funcsig_mappings as grib_util_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_expression_stub_funcsig_mappings as grib_expression_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_parse_utils_stub_funcsig_mappings as grib_parse_utils_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_context_stub_funcsig_mappings as grib_context_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_value_stub_funcsig_mappings as grib_value_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_ieeefloat_stub_funcsig_mappings as grib_ieeefloat_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_optimize_decimal_factor_stub_funcsig_mappings as grib_optimize_decimal_factor_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_scaling_stub_funcsig_mappings as grib_scaling_stub_funcsig_mappings
import grib_accessor.supporting.funcsig_mappings.grib_stub_funcsig_mappings.grib_errors_stub_funcsig_mappings as grib_errors_stub_funcsig_mappings

grib_stub_funcsig_mappings = [
    grib_accessor_class_stub_funcsig_mappings.grib_accessor_class_stub_funcsig_mappings,
    grib_accessor_stub_funcsig_mappings.grib_accessor_stub_funcsig_mappings,
    grib_bits_any_endian_stub_funcsig_mappings.grib_bits_any_endian_stub_funcsig_mappings,
    grib_buffer_stub_funcsig_mappings.grib_buffer_stub_funcsig_mappings,
    grib_date_stub_funcsig_mappings.grib_date_stub_funcsig_mappings,
    grib_util_stub_funcsig_mappings.grib_util_stub_funcsig_mappings,
    grib_expression_stub_funcsig_mappings.grib_expression_stub_funcsig_mappings,
    grib_parse_utils_stub_funcsig_mappings.grib_parse_utils_stub_funcsig_mappings,
    grib_context_stub_funcsig_mappings.grib_context_stub_funcsig_mappings,
    grib_value_stub_funcsig_mappings.grib_value_stub_funcsig_mappings,
    grib_ieeefloat_stub_funcsig_mappings.grib_ieeefloat_stub_funcsig_mappings,
    grib_optimize_decimal_factor_stub_funcsig_mappings.grib_optimize_decimal_factor_stub_funcsig_mappings,
    grib_scaling_stub_funcsig_mappings.grib_scaling_stub_funcsig_mappings,
    grib_errors_stub_funcsig_mappings.grib_errors_stub_funcsig_mappings,
]

# Return a list of all the funcsig conversions
def all_grib_stub_funcsig_mappings():
    return grib_stub_funcsig_mappings
