[package]
name = "eccodes"
prefix = "eccodes"
repo = "ecmwf/eccodes"
visibility = "public"
compiler-inputs = ["cxx-compiler", "fortran-compiler"]

[[deps]]
repo = "ecmwf/ecbuild"
package = "ecbuild"
ref = "develop"
compiler-inputs = []

[[deps]]
repo = "ecmwf/stack-dependencies"
package = "stack-deps"
ref = "master"
compiler-inputs = ["cxx-compiler"]

[[deps]]
repo = "ecmwf/eckit"
package = "eckit"
ref = "develop"
compiler-inputs = ["cxx-compiler"]
when = { options = ["eckit-geo"] }

[[matrix.build.include]]
cxx-compiler = "clang++-18"
build-type = "Release"
fortran-compiler = "gfortran-13"
runs-on = "arc-runner-very-large"
container = "eccr.ecmwf.int/public-ci-images/ubuntu24.04-clang18-gfortran13:latest"
platform = "ubuntu-24.04"

[[matrix.build.include]]
cxx-compiler = "g++-13"
build-type = "Release"
fortran-compiler = "gfortran-13"
runs-on = "arc-runner-very-large"
container = "eccr.ecmwf.int/public-ci-images/ubuntu24.04-clang18-gfortran13:latest"
platform = "ubuntu-24.04"

[[matrix.build.include]]
cxx-compiler = "g++-13"
build-type = "Release"
fortran-compiler = "gfortran-13"
options = "eckit-geo"
runs-on = "arc-runner-very-large"
container = "eccr.ecmwf.int/public-ci-images/ubuntu24.04-clang18-gfortran13:latest"
platform = "ubuntu-24.04"

[matrix.build]
triggers = ["upstream-change", "rebuild-request"]
action = "./.github/actions/build-eccodes"
forwarded-inputs = ["cxx-compiler", "fortran-compiler", "build-type", "options"]
forwarded-deps-outputs = ["cmake-prefix-path"]
needs = ["ecbuild/build", "stack-deps/build", "eckit/build"]
ctest = true
ctest-args = '-j "$(nproc)"'

[[matrix.build-hpc.include]]
cxx-compiler = "g++-8"
fortran-compiler = "gfortran-8"
build-type = "Release"
runs-on = "hpc-submit"
container = "eccr.ecmwf.int/private-ci-images/ubuntu24.04-internal-tools:latest"
site = "hpc-batch"
platform = "hpc-atos-gnu"
job-script = "./.ci/hpc/build-gnu.sh"

[[matrix.build-hpc.include]]
cxx-compiler = "g++-8"
fortran-compiler = "gfortran-8"
build-type = "Release"
options = "eckit-geo"
runs-on = "hpc-submit"
container = "eccr.ecmwf.int/private-ci-images/ubuntu24.04-internal-tools:latest"
site = "hpc-batch"
platform = "hpc-atos-gnu"
job-script = "./.ci/hpc/build-eckit-geo.sh"

[matrix.build-hpc]
execution = "hpc"
container-credentials = true
job-script = "./.ci/hpc/build-gnu.sh"
triggers = ["upstream-change", "rebuild-request"]
forwarded-deps-outputs = ["cmake-prefix-path"]
needs = ["ecbuild/build-hpc", "stack-deps/build-hpc", "eckit/build-hpc"]
