use strict;

# ------------------------------------------------------------------------
# Get the CodeFlag.txt file from WMO
# Convert it to TSV (tab-separated-values format):
#  perl csv_2_tsv.pl CodeFlag.txt
# This will create the file CodeFlag.txt.tsv
# Create the directory corresponding to the new GRIB2 version:
#  mkdir -p definitions/grib2/tables/xx
# cd to that directory:
#  cd definitions/grib2/tables/xx
# Run this script on that TSV file:
#  perl create_grib2_codetables.pl < /path/to/CodeFlag.txt.tsv
# This should create all the *.table files
# ------------------------------------------------------------------------

# The WMO CSV file should have the following columns
#   Title_en
#   SubTitle_en
#   CodeFlag
#   Value
#   MeaningParameterDescription_en
#   Note_en
#   noteIDs
#   UnitComments_en
#   Status

my $EXPECTED_COLUMN_COUNT = 9; # As of v29; May 2022
my $recnum = 0;
my $codetable;
my $discipline;
my $category;
my $filename;

while (<>) {
    ++$recnum;
    if ($recnum == 1) {
        my @columns = split(/\t/);
        my $column_count = @columns;
        if ($column_count != $EXPECTED_COLUMN_COUNT) {
            die "Error: Incorrect column count on first row. Expected $EXPECTED_COLUMN_COUNT but found $column_count!\n";
        }
        next;
    }

    s/Hovmöller/Hovmoller/;
    s/Carrée/Carree/;
    s/μm/um/;
    s/°C/degree C/;
    s/f\(n\) = C2 × f\(n-1\)/f(n) = C2 * f(n-1)/;
    s/\(see separate doc or pdf file\)/see separate doc or pdf file/;

    my ($title, $subtitle, $codeFlag, $value, $meaning, $note, $noteID, $unit, $status) = split(/\t/);

    if ($title =~ /Code table ([0-9.]+)/) {
        $codetable = $1;
        if ($subtitle =~ /Product [Dd]iscipline (\d+).*parameter category (\d+)/) {
            $discipline = $1;
            $category = $2;
            $filename = "$codetable.$discipline.$category.table";
            WriteFile($filename, $subtitle, $codeFlag, $meaning, $unit);
        }
        elsif ($subtitle =~ /Product discipline (\d+)/) {
            $discipline = $1;
            $filename = "$codetable.$discipline.table";
            WriteFile($filename, $subtitle, $codeFlag, $meaning, $unit);
        }
        elsif ($subtitle eq "") {
            $filename = "$codetable.table";
            WriteFile($filename, $title, $codeFlag, $meaning, $unit);
        }
    } elsif ($title =~ /Flag table ([0-9.]+)/) {
        $codetable = $1;
        $filename = "$codetable.table";
        WriteFlagTable($filename, $title, $codeFlag, $value, $meaning, $unit);
    }

    #exit if ($recnum >800);
}
###################################################################################################
sub WriteFile {
    my($filename, $title, $codeFlag, $meaning, $unit) = @_;
    if (!-e $filename) {
        print "Creating $filename\n";
        open (MYFILE, ">>$filename");
        #print MYFILE "# Automatically generated by ./create_tables.pl from database fm92_grib2\@wrep-db-misc-prod, do not edit\n";
        print MYFILE "# $title\n";
    }
    my $unit_text = ($unit eq "" ? "" : "($unit)");
    $unit_text =~ s/\(\(Code /(Code /;
    $unit_text =~ s/\)\)/)/;
    if ($codeFlag =~ /\-/) {
        if ($unit_text eq "") {
            print MYFILE "# $codeFlag $meaning\n";
        } else {
            print MYFILE "# $codeFlag $meaning $unit_text\n";
        }
    } else {
        my $codeFlag1 = $codeFlag; # A number
        my $codeFlag2 = $codeFlag; # A number or string abbreviation
        if ($filename eq "1.4.table") {
            # Special case. Do not just put 2nd code, translate it to shortName for 'mars type'
            $codeFlag2 = TranslateCodes_Table_1_4($codeFlag);
        }
        elsif ($filename eq "3.12.table") {
            $codeFlag2 = TranslateCodes_Table_3_12($codeFlag);
        }
        elsif ($filename eq "3.15.table") {
            $codeFlag2 = TranslateCodes_Table_3_15($codeFlag);
        }
        elsif ($filename eq "4.4.table") {
            $codeFlag2 = TranslateCodes_Table_4_4($codeFlag);
        }
        elsif ($filename eq "4.5.table") {
            $codeFlag2 = TranslateCodes_Table_4_5($codeFlag);
        }
        elsif ($filename eq "4.241.table") {
            $codeFlag2 = TranslateCodes_Table_4_241($codeFlag);
        }
        elsif ($filename eq "4.242.table") {
            $codeFlag2 = TranslateCodes_Table_4_242($codeFlag);
        }
        elsif ($filename eq "4.252.table") {
            $codeFlag2 = TranslateCodes_Table_4_252($codeFlag);
        }
        elsif ($filename eq "4.10.table") {
            $codeFlag2 = TranslateCodes_Table_4_10($codeFlag);
        }

        if ($unit_text eq "") {
            print MYFILE "$codeFlag1 $codeFlag2 $meaning\n";
        } else {
            print MYFILE "$codeFlag1 $codeFlag2 $meaning $unit_text\n";
        }
    }
}

###################################################################################################
sub WriteFlagTable{
    my($filename, $title, $codeFlag, $value, $meaning, $unit) = @_;
    if (!-e $filename) {
        print "Creating $filename\n";
        open (MYFILE, ">>$filename");
        #print MYFILE "# Automatically generated by ./create_tables.pl from database fm92_grib2\@wrep-db-misc-prod, do not edit\n";
        print MYFILE "# $title\n";
    }
    my $unit_text = ($unit eq "" ? "" : " ($unit)");
    if ($codeFlag =~ /\-/) {
        print MYFILE "# $codeFlag $meaning$unit_text\n";
    } else {
        print MYFILE "$codeFlag $value $meaning$unit_text\n";
    }
}

###################################################################################################
sub TranslateCodes_Table_4_10 {
    my ($code) = @_;
    return "avg"   if ($code == 0);
    return "accum" if ($code == 1);
    return "max"   if ($code == 2);
    return "min"   if ($code == 3);
    return "diff"  if ($code == 4);
    return "rms"   if ($code == 5);
    return "sd"    if ($code == 6);
    return "cov"   if ($code == 7);
    return "ratio" if ($code == 9);
    return "missing" if ($code == 255);
    return $code;
}

sub TranslateCodes_Table_3_12 {
    my ($code) = @_;
    return "ring" if ($code == 0);
    return "nested" if ($code == 1);
    return $code;
}

sub TranslateCodes_Table_3_15 {
    my ($code) = @_;
    return "pt" if ($code == 107);
    return "pv" if ($code == 109);
    return $code;
}

sub TranslateCodes_Table_1_4 {
    my ($code) = @_;
    return "an" if ($code eq "0");
    return "fc" if ($code eq "1");
    return "af" if ($code eq "2");
    return "cf" if ($code eq "3");
    return "pf" if ($code eq "4");
    return "cp" if ($code eq "5");
    return "sa" if ($code eq "6");
    return "ra" if ($code eq "7");
    return "ep" if ($code eq "8");
    return "missing" if ($code eq "255");
    return $code;
}

sub TranslateCodes_Table_4_4 {
    my ($code) = @_;
    return "m"    if ($code eq "0");
    return "h"    if ($code eq "1");
    return "D"    if ($code eq "2");
    return "M"    if ($code eq "3");
    return "Y"    if ($code eq "4");
    return "10Y"  if ($code eq "5");
    return "30Y"  if ($code eq "6");
    return "C"    if ($code eq "7");
    return "3h"   if ($code eq "10");
    return "6h"   if ($code eq "11");
    return "12h"  if ($code eq "12");
    return "s"    if ($code eq "13");
    return $code;
}

sub TranslateCodes_Table_4_5 {
    my ($code) = @_;
    return "sfc"  if ($code eq "1" || $code eq "7" ||
            $code eq "8"   || $code eq "17"  || $code eq "18"  ||
            $code eq "101" || $code eq "103" || $code eq "106" ||
            $code eq "162" || $code eq "166" || $code eq "174" ||
            $code eq "177");
    return "pl"   if ($code eq "100");
    return "ml"   if ($code eq "105");
    return "pt"   if ($code eq "107");
    return "pv"   if ($code eq "109");
    return "hhl"  if ($code eq "118");
    return "hpl"  if ($code eq "119");
    return "sol"  if ($code eq "151");
    return "sol"  if ($code eq "114");
    return "sol"  if ($code eq "152");
    return $code;
}

sub TranslateCodes_Table_4_241 {
    my ($code) = @_;
    return "undef"  if ($code eq "0");
    return "unmod"  if ($code eq "1");
    return "snow"   if ($code eq "2");
    return "flood"  if ($code eq "3");
    return "ice"    if ($code eq "4");
    return "itcw"   if ($code eq "5");
    return "itcs"   if ($code eq "6");
    return "agg"    if ($code eq "7");
    return $code;
}

sub TranslateCodes_Table_4_242 {
    my ($code) = @_;

    return "GCV2009"      if ($code eq "1");
    return "GLC2000"      if ($code eq "2");
    return "ECOCLIMAP"    if ($code eq "3");
    return "ECOCLIMAP-SG" if ($code eq "4");
    return "GLCCv2BATS"   if ($code eq "5");
    return $code;
}

sub TranslateCodes_Table_4_252 {
    my ($code) = @_;

    return "seoc" if ($code eq "1");
    return "inwb" if ($code eq "2");
    return "bare" if ($code eq "3");
    return "hiv" if ($code eq "4");
    return "lov" if ($code eq "5");
    return "urban" if ($code eq "6");
    return "seao" if ($code eq "1001");
    return "lake" if ($code eq "1002");
    return "rive" if ($code eq "1003");
    return "no" if ($code eq "1004");
    return "rock" if ($code eq "1005");
    return "snow" if ($code eq "1006");
    return "bobd" if ($code eq "1007");
    return "tebd" if ($code eq "1008");
    return "trbd" if ($code eq "1009");
    return "tebe" if ($code eq "1010");
    return "trbe" if ($code eq "1011");
    return "bone" if ($code eq "1012");
    return "tene" if ($code eq "1013");
    return "bond" if ($code eq "1014");
    return "shrb" if ($code eq "1015");
    return "bogr" if ($code eq "1016");
    return "gras" if ($code eq "1017");
    return "trog" if ($code eq "1018");
    return "c3w" if ($code eq "1019");
    return "c3s" if ($code eq "1020");
    return "c4" if ($code eq "1021");
    return "fltr" if ($code eq "1022");
    return "flgr" if ($code eq "1023");
    return "lcz1" if ($code eq "1024");
    return "lcz2" if ($code eq "1025");
    return "lcz3" if ($code eq "1026");
    return "lcz4" if ($code eq "1027");
    return "lcz5" if ($code eq "1028");
    return "lcz6" if ($code eq "1029");
    return "lcz7" if ($code eq "1030");
    return "lcz8" if ($code eq "1031");
    return "lcz9" if ($code eq "1032");
    return "lcz10" if ($code eq "1033");
    return "tebdu" if ($code eq "1034");
    return "trbdu" if ($code eq "1035");
    return "tebeu" if ($code eq "1036");
    return "trbeu" if ($code eq "1037");
    return "boneu" if ($code eq "1038");
    return "teneu" if ($code eq "1039");
    return "bondu" if ($code eq "1040");
    return "gnatu" if ($code eq "1501");
    return "gnofo" if ($code eq "1502");
    return "gfore" if ($code eq "1503");
    return "gnove" if ($code eq "1504");
    return "gtree" if ($code eq "1505");
    return "glveg" if ($code eq "1506");
    return "gnflv" if ($code eq "1507");
    return "gcrop" if ($code eq "1508");
    return "ggras" if ($code eq "1509");
    return "gbaro" if ($code eq "1510");
    return "gc3cr" if ($code eq "1511");
    return "gbfor" if ($code eq "1512");
    return "gnfor" if ($code eq "1513");
    return "gdbfo" if ($code eq "1514");
    return "gtgra" if ($code eq "1515");
    return "gnfnf" if ($code eq "1516");
    return "gbfft" if ($code eq "1517");
    return "gbtre" if ($code eq "1518");
    return "gcgra" if ($code eq "1519");
    return "gbdtr" if ($code eq "1520");
    return "gbetr" if ($code eq "1521");
    return "gnetr" if ($code eq "1522");
    return "glczu" if ($code eq "1523");
    return "giwat" if ($code eq "1524");
    return "gptebd" if ($code eq "1525");
    return "gptrbd" if ($code eq "1526");
    return "gptebe" if ($code eq "1527");
    return "gptrbe" if ($code eq "1528");
    return "gpbone" if ($code eq "1529");
    return "gptene" if ($code eq "1530");
    return "gpbond" if ($code eq "1531");
    return "crmf" if ($code eq "2001");
    return "shgr" if ($code eq "2002");
    return "evne" if ($code eq "2003");
    return "dene" if ($code eq "2004");
    return "debr" if ($code eq "2005");
    return "evbr" if ($code eq "2006");
    return "tagr" if ($code eq "2007");
    return "dese" if ($code eq "2008");
    return "tund" if ($code eq "2009");
    return "ircr" if ($code eq "2010");
    return "sede" if ($code eq "2011");
    return "icgl" if ($code eq "2012");
    return "boma" if ($code eq "2013");
    return "inwa" if ($code eq "2014");
    return "ocea" if ($code eq "2015");
    return "evsh" if ($code eq "2016");
    return "desh" if ($code eq "2017");
    return "mfwo" if ($code eq "2018");
    return "info" if ($code eq "2019");
    return "wlmi" if ($code eq "2020");
    return "baso" if ($code eq "2021");
    return "urba" if ($code eq "2022");
    return "lori" if ($code eq "2023");
    return "hiri" if ($code eq "2024");
    return "glve" if ($code eq "2501");
    return "ghve" if ($code eq "2502");
    return "pfic" if ($code eq "3001");
    return "racr" if ($code eq "3002");
    return "mcve" if ($code eq "3003");
    return "mvcr" if ($code eq "3004");
    return "cobs" if ($code eq "3005");
    return "clbd" if ($code eq "3006");
    return "opbd" if ($code eq "3007");
    return "clne" if ($code eq "3008");
    return "onde" if ($code eq "3009");
    return "cobn" if ($code eq "3010");
    return "mfsg" if ($code eq "3011");
    return "mgfs" if ($code eq "3012");
    return "cosh" if ($code eq "3013");
    return "cohv" if ($code eq "3014");
    return "spve" if ($code eq "3015");
    return "cobff" if ($code eq "3016");
    return "clbff" if ($code eq "3017");
    return "covef" if ($code eq "3018");
    return "asaa" if ($code eq "3019");
    return "baar" if ($code eq "3020");
    return "wabo" if ($code eq "3021");
    return "pesi" if ($code eq "3022");
    return "grdt" if ($code eq "3501");
    return "tbeco" if ($code eq "4001");
    return "tbdc" if ($code eq "4002");
    return "tbdo" if ($code eq "4003");
    return "tneco" if ($code eq "4004");
    return "tndco" if ($code eq "4005");
    return "tmlco" if ($code eq "4006");
    return "tcoff" if ($code eq "4007");
    return "tcofs" if ($code eq "4008");
    return "mtvg" if ($code eq "4009");
    return "tburn" if ($code eq "4010");
    return "scoe" if ($code eq "4011");
    return "scod" if ($code eq "4012");
    return "hcco" if ($code eq "4013");
    return "shsc" if ($code eq "4014");
    return "fshco" if ($code eq "4015");
    return "crop" if ($code eq "4016");
    return "mctnv" if ($code eq "4017");
    return "mcsh" if ($code eq "4018");
    return "baare" if ($code eq "4019");
    return "wbna" if ($code eq "4020");
    return "sina" if ($code eq "4021");
    return "urar" if ($code eq "4022");
    return $code;
}
