#!/bin/sh

keys="md5Structure,md5Data,typicalDate,typicalTime,rdbType,rdbSubtype,ident,satelliteID,localLatitude,localLongitude,localLatitude1,localLongitude1,localLatitude2,localLongitude2"

opt=""

if [ $# -eq 3  ]
then
  opt=$1
  dir1=$2
  dir2=$3
fi

if [ $# -eq 2 ]
then
  dir1=$1
  dir2=$2
fi

if [ $# -gt 3 ] || [ $# -lt 2 ]
then
  echo usage: [bufr_compare options] bufr_compare_dir directory1 directory2
  exit 1
fi

bufr_index_build -k $keys -o 1.idx "$dir1"/* > /dev/null
bufr_index_build -k $keys -o 2.idx "$dir2"/* > /dev/null

bufr_compare -f $opt 1.idx 2.idx
rm -f 1.idx 2.idx

