/* This file is automatically generated by ./make_class.pl, do not edit */
extern grib_box_class* grib_box_class_gen;
extern grib_box_class* grib_box_class_reduced_gaussian;
extern grib_box_class* grib_box_class_regular_gaussian;
