
#line 3 "lex.grib_yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define grib_yyconst const
#else
#define grib_yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (grib_yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((grib_yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE grib_yyrestart(grib_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(grib_yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct grib_yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int grib_yyleng;

extern FILE *grib_yyin, *grib_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define grib_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up grib_yytext. */ \
        int grib_yyless_macro_arg = (n); \
        YY_LESS_LINENO(grib_yyless_macro_arg);\
		*grib_yy_cp = (grib_yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(grib_yy_c_buf_p) = grib_yy_cp = grib_yy_bp + grib_yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up grib_yytext again */ \
		} \
	while ( 0 )

#define unput(c) grib_yyunput( c, (grib_yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t grib_yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct grib_yy_buffer_state
	{
	FILE *grib_yy_input_file;

	char *grib_yy_ch_buf;		/* input buffer */
	char *grib_yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	grib_yy_size_t grib_yy_buf_size;

	/* Number of characters read into grib_yy_ch_buf, not including EOB
	 * characters.
	 */
	int grib_yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int grib_yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int grib_yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int grib_yy_at_bol;

    int grib_yy_bs_lineno; /**< The line count. */
    int grib_yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int grib_yy_fill_buffer;

	int grib_yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via grib_yyrestart()), so that the user can continue scanning by
	 * just pointing grib_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t grib_yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t grib_yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * grib_yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (grib_yy_buffer_stack) \
                          ? (grib_yy_buffer_stack)[(grib_yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (grib_yy_buffer_stack)[(grib_yy_buffer_stack_top)]

/* grib_yy_hold_char holds the character lost when grib_yytext is formed. */
static char grib_yy_hold_char;
static int grib_yy_n_chars;		/* number of characters read into grib_yy_ch_buf */
int grib_yyleng;

/* Points to current character in buffer. */
static char *grib_yy_c_buf_p = (char *) 0;
static int grib_yy_init = 0;		/* whether we need to initialize */
static int grib_yy_start = 0;	/* start state number */

/* Flag which is used to allow grib_yywrap()'s to do buffer switches
 * instead of setting up a fresh grib_yyin.  A bit of a hack ...
 */
static int grib_yy_did_buffer_switch_on_eof;

void grib_yyrestart (FILE *input_file  );
void grib_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE grib_yy_create_buffer (FILE *file,int size  );
void grib_yy_delete_buffer (YY_BUFFER_STATE b  );
void grib_yy_flush_buffer (YY_BUFFER_STATE b  );
void grib_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void grib_yypop_buffer_state (void );

static void grib_yyensure_buffer_stack (void );
static void grib_yy_load_buffer_state (void );
static void grib_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER grib_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE grib_yy_scan_buffer (char *base,grib_yy_size_t size  );
YY_BUFFER_STATE grib_yy_scan_string (grib_yyconst char *grib_yy_str  );
YY_BUFFER_STATE grib_yy_scan_bytes (grib_yyconst char *bytes,int len  );

void *grib_yyalloc (grib_yy_size_t  );
void *grib_yyrealloc (void *,grib_yy_size_t  );
void grib_yyfree (void *  );

#define grib_yy_new_buffer grib_yy_create_buffer

#define grib_yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        grib_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->grib_yy_is_interactive = is_interactive; \
	}

#define grib_yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        grib_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->grib_yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->grib_yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *grib_yyin = (FILE *) 0, *grib_yyout = (FILE *) 0;

typedef int grib_yy_state_type;

extern int grib_yylineno;

int grib_yylineno = 1;

extern char *grib_yytext;
#define grib_yytext_ptr grib_yytext

static grib_yy_state_type grib_yy_get_previous_state (void );
static grib_yy_state_type grib_yy_try_NUL_trans (grib_yy_state_type current_state  );
static int grib_yy_get_next_buffer (void );
static void grib_yy_fatal_error (grib_yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up grib_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(grib_yytext_ptr) = grib_yy_bp; \
	grib_yyleng = (size_t) (grib_yy_cp - grib_yy_bp); \
	(grib_yy_hold_char) = *grib_yy_cp; \
	*grib_yy_cp = '\0'; \
	(grib_yy_c_buf_p) = grib_yy_cp;

#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct grib_yy_trans_info
	{
	flex_int32_t grib_yy_verify;
	flex_int32_t grib_yy_nxt;
	};
static grib_yyconst flex_int16_t grib_yy_accept[507] =
    {   0,
       99,   99,  103,  101,   99,  100,   12,   93,   98,  101,
      101,   96,    5,  101,    3,   95,   95,   95,   94,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,  101,
       18,   99,    6,   14,    0,    0,   96,    4,    7,    1,
        2,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   20,   95,   10,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       15,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   95,   95,   95,   95,   95,   16,   97,   95,   21,
       95,   13,   95,   95,   95,    8,   57,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   32,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       11,   95,   95,   45,   95,   95,   95,   95,   95,   80,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,    0,   95,   95,   95,   95,   95,   25,   95,
       83,   95,   95,   95,   95,   95,   95,   72,   95,   22,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   58,   95,   95,   27,   95,   95,   95,   95,   41,
       95,   95,   95,   95,   95,   17,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   91,   95,   95,   95,   95,
       95,   95,   95,   82,   95,   95,    0,   97,   95,   48,
       95,   24,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   39,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   26,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   43,   95,   90,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   28,   88,   95,   89,   68,   95,   95,   95,   95,

       95,   95,   95,   95,   95,   65,   95,   95,   95,   95,
       37,   74,   95,   95,   95,   95,   95,   67,   95,   40,
       95,   95,   61,   95,   95,   95,    9,   95,   95,   95,
       95,   95,   66,   95,   95,   35,   95,   84,   95,   95,
       95,   95,   95,   76,   95,   95,   95,   86,   95,   95,
       79,   85,   95,   59,   95,   95,   95,   95,   95,   92,
       95,   95,   95,   95,   47,   56,   70,   73,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   31,   49,
       95,   95,   95,   95,   95,   51,   95,   95,   95,   95,
       95,   33,   95,   55,   95,   95,   95,   78,   95,   95,

       50,   95,   95,   95,   95,   29,   95,   23,   95,   36,
       95,   95,   95,   95,   95,   95,   95,   34,   95,   54,
       19,   42,   95,   69,   95,   95,   95,   95,   52,   95,
       95,   95,   77,   95,   95,   95,   95,   95,   95,   95,
       81,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       60,   95,   95,   53,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   44,   95,   95,   75,   95,   87,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   46,
       30,   95,   71,   95,   95,   95,   38,   95,   63,   95,

       95,   64,   95,   95,   62,    0
    } ;

static grib_yyconst flex_int32_t grib_yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    8,    1,
        1,    1,    9,    1,    9,   10,    1,   11,   12,   11,
       11,   13,   11,   11,   11,   11,   11,    1,    1,   14,
       15,   16,    1,    1,   17,   17,   17,   17,   18,   17,
       19,   17,   20,   17,   17,   17,   21,   22,   17,   17,
       17,   17,   23,   17,   17,   17,   17,   17,   17,   17,
        1,    1,    1,    1,   24,   25,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   17,   35,   36,   37,   38,
       39,   40,   17,   41,   42,   43,   44,   45,   46,   47,
       48,   17,    1,   49,    1,   50,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static grib_yyconst flex_int32_t grib_yy_meta[51] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    2,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1
    } ;

static grib_yyconst flex_int16_t grib_yy_base[509] =
    {   0,
        0,    0,  324, 2045,  321, 2045,  302, 2045, 2045,  309,
       40,   44,   43,  299,  298,   49,   52,   55, 2045,   58,
       63,   66,   69,   72,   48,  104,  109,  117,   87,  124,
      112,  135,  155,  146,  147,  158,  164,  195,  198,  256,
     2045,  302, 2045, 2045,  120,  128,  202, 2045, 2045, 2045,
     2045,    0,  205,  209,  212,  215,  223,  229,  233,  242,
      245,  251,  230,  242,  275,  278,  284,  287,  290,  296,
      299,  269,  309,  315,  319,  327,  322,  330,  334,  337,
      342,  348,  351,  357,  365,  370,  373,  379,  382,  385,
      396,  403,  406,  411,  415,  418,  426,  429,  434,  439,

      445,  451,  444,  447,  461,  464, 2045,  454,  493,  496,
      499,  502,  506,  509,  515,  518,  521,  526,  529,  535,
      538,  546,  549,  558,  561,  567,  570,  581,  577,  584,
      587,  459,  590,  597,  603,  616,  619,  624,  628,  631,
      636,  639,  646,  651,  658,  661,  664,  668,  672,  680,
      683,  686,  693,  703,  706,  712,  715,  718,  724,  730,
      736,  740,  747,  750,  757,  753,  760,  764,  771,  774,
      777,  783,  790,  795,  798,  805,  808,  811,  816,  819,
      822,  825,  836,  843,  846,  850,  853,  858,  864,  867,
      870,  873,  257,  251,  247,  879,  882,  890,  893,  896,

      907,  910,  916,  919,  923,  926,  930,  934,  942,  945,
      948,  952,  958,  965,  972,  975,  981,  987,  990,  996,
      999, 1002, 1006, 1016, 1019, 1023, 1030, 1033, 1039, 1044,
     1047, 1051, 1058, 1054, 1061, 1065, 1069, 1076, 1081, 1085,
     1088, 1093, 1096, 1099, 1102, 1107, 1110, 1114, 1119, 1123,
     1130, 1133, 1136, 1140,  240,  232,  245, 1149, 1152, 1160,
     1155, 1166, 1169,  237, 1172, 1175, 1185, 1189, 1192, 1198,
     1202, 1205, 1211, 1214, 1220, 1223, 1228, 1232, 1241, 1248,
     1256, 1259, 1262, 1265, 1268, 1271, 1277, 1280, 1294, 1284,
     1300, 1304, 1307, 1310, 1314, 1319, 1322, 1328, 1331, 1336,

     1339, 1345, 1348, 1351, 1354, 1357, 1361,  234,  218,  216,
     1369, 1373, 1376, 1384, 1387, 1394,  204, 1397, 1400, 1403,
     1408, 1413, 1416, 1419, 1424, 1427, 1433, 1438, 1441, 1444,
     1448, 1453, 1457, 1462, 1465, 1468, 1471, 1481, 1486, 1490,
     1493, 1496, 1500, 1503, 1506, 1510, 1513, 1520, 1528, 1536,
     1539, 1542, 1545, 1548,  226,  222,  213, 1551, 1554, 1561,
     1564,  198, 1570, 1573, 1576, 1579, 1584, 1587, 1590, 1595,
     1600, 1605, 1610, 1615, 1618, 1621, 1629, 1636, 1639, 1642,
     1649, 1645, 1654, 1657, 1660, 1664, 1669, 1675,  210,  198,
      190, 1678, 1681, 1684,  174, 1688, 1691, 1697, 1700, 1703,

     1714, 1717, 1720, 1723, 1728, 1731, 1736, 1739, 1750, 1755,
     1758, 1761, 1769, 1773,  154,  169,  157, 1776,  161, 1782,
     1790, 1793, 1796, 1803, 1806, 1809, 1812, 1815, 1822, 1825,
     1828, 1831, 1835, 1838,  146,  159,  169,  137, 1843, 1847,
     1852, 1858, 1861, 1867, 1873, 1878, 1881,  145,  135,  146,
        0, 1884, 1894, 1899, 1902, 1905, 1913, 1916, 1919,  140,
      132,  120, 1924, 1927, 1933, 1936, 1951, 1954, 1958,  124,
      111,  115, 1961, 1967, 1970, 1973, 1980, 1983, 1986,   89,
       94,   86, 1989, 1997, 2000, 2003,   89,   66,   75, 2006,
     2011, 2014, 2017,   76,   71,   60, 2026,   64,    0,   60,

       55,    0,   61,   53,    0, 2045,   81,   71
    } ;

static grib_yyconst flex_int16_t grib_yy_def[509] =
    {   0,
      506,    1,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  507,  507,  507,  506,  507,
      507,  507,  507,   20,   20,  507,  507,   20,   20,  507,
       30,   30,  507,   30,   30,   30,   30,  507,  507,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  508,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,   20,   20,  507,  507,  507,  507,  507,  507,
      507,  508,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,

      507,  507,   30,   30,   30,   30,  506,  506,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  508,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  506,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  508,  508,  508,  507,  507,  507,  507,  507,

      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  506,  506,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  508,  508,  508,  507,  507,  507,
      507,  507,  507,  508,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,

      507,  507,  507,  507,  507,  507,  507,  508,  508,  508,
      507,  507,  507,  507,  507,  507,  508,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  508,  508,  508,  507,  507,  507,
      507,  508,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  508,  508,
      508,  507,  507,  507,  508,  507,  507,  507,  507,  507,

      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  508,  508,  508,  507,  508,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  508,  508,  508,  508,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  508,  508,  508,
      508,  507,  507,  507,  507,  507,  507,  507,  507,  508,
      508,  508,  507,  507,  507,  507,  507,  507,  507,  508,
      508,  508,  507,  507,  507,  507,  507,  507,  507,  508,
      508,  508,  507,  507,  507,  507,  508,  508,  508,  507,
      507,  507,  507,  508,  508,  508,  507,  508,  508,  508,

      508,  508,  508,  508,  508,    0,  506,  506
    } ;

static grib_yyconst flex_int16_t grib_yy_nxt[2096] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    8,   11,    4,
       12,   12,   12,   13,   14,   15,   16,   16,   16,   16,
       17,   16,   16,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   16,   39,   16,   16,   40,   41,
       45,   45,   45,   46,   47,   47,   47,   48,   49,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   54,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   53,   71,  505,   53,  504,   53,   55,   53,
      503,   63,  502,   56,  501,   57,   60,   58,   65,   59,

       67,   61,  500,  499,   64,  498,  496,   68,  495,   69,
       62,   53,   66,   53,   52,   72,   52,  494,   70,   52,
       52,   52,   53,  489,   53,  488,   53,  487,   81,   46,
       45,   45,   45,   73,   52,   52,   52,   53,  108,  108,
      108,   86,   74,   75,  482,   53,   76,   77,  481,   82,
       87,  480,   53,   83,   78,  472,   53,   84,   79,   80,
       53,  471,   85,  470,   88,   52,   52,   52,   53,  462,
      461,   93,   53,   89,  460,   53,   96,  451,   90,   53,
       53,  450,  449,   53,   94,   53,   95,   97,  448,   53,
      438,   98,   99,  102,  437,   91,   53,   53,  436,   92,

      100,  435,   53,  101,  103,   52,   52,   52,   52,   52,
       52,   46,   47,   47,   47,   52,   52,   52,  419,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  417,  416,
      105,  109,  104,   52,   52,   52,  415,  395,  106,   52,
       52,   52,  110,   52,   52,   52,  391,  390,  111,  389,
      362,  112,   52,   52,   52,   52,   52,   52,  357,  356,
      114,   52,   52,   52,  355,   53,  317,  119,  113,   53,
      121,  120,  310,  309,  115,  308,  257,   53,  122,  123,
      256,  124,  255,   53,  116,   52,   52,   52,   52,   52,
       52,  117,  132,  118,   52,   52,   52,   52,   52,   52,

       52,   52,   52,   42,  107,  125,   52,   52,   52,   52,
       52,   52,   51,   50,  126,   44,   43,  127,  129,   52,
       52,   52,   42,  506,  131,   52,   52,   52,  128,   52,
       52,   52,   52,   52,   52,  130,  506,   52,   52,   52,
       52,   52,   52,  134,   52,   52,   52,   52,   52,   52,
      506,  133,   52,   52,   52,  135,  136,  137,   52,   52,
       52,   52,   52,   52,  506,  506,  138,   52,   52,   52,
      506,  139,  506,  506,  140,   52,   52,   52,  506,  506,
       52,   52,   52,   52,   52,   52,  506,  506,  141,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  142,  506,

      506,  148,  143,  144,  149,  150,   52,   52,   52,  506,
      145,  146,  147,   52,   52,   52,   52,   52,   52,  506,
      152,   52,   52,   52,  151,   52,   52,   52,   52,   52,
       52,  506,  153,  506,  154,  506,   52,   52,   52,   52,
       52,   52,  506,  157,   52,   52,   52,  506,  156,   52,
       52,   52,  155,  159,  158,   52,   52,   52,  506,  506,
      161,   52,   52,   52,  108,  108,  108,  162,  160,  166,
      506,  173,  168,   53,  506,  506,   53,  167,  164,  163,
       53,  506,   53,  173,  506,   53,   53,  165,  169,   53,
      170,  193,  506,   53,  171,  194,  506,  172,  506,   53,

      195,  506,   53,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,  174,   52,   52,   52,   52,
       52,   52,  506,  506,  175,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  506,  176,   52,   52,   52,   52,
       52,   52,  177,  506,  178,   52,   52,   52,   52,   52,
       52,  506,  180,  506,  506,  179,   52,   52,   52,   52,
       52,   52,  506,  506,  181,  506,  506,  182,   52,   52,
       52,   52,   52,   52,  506,  506,  184,   52,   52,   52,
       52,   52,   52,  506,  506,  183,  187,   52,   52,   52,
      185,   52,   52,   52,   52,   52,   52,   52,   52,   52,

       52,   52,   52,  506,  506,  186,  188,   52,   52,   52,
      190,  506,  189,   52,   52,   52,  506,  506,  192,  196,
      506,  506,  191,  506,  506,  197,   52,   52,   52,   52,
       52,   52,  506,  198,   52,   52,   52,  506,   52,   52,
       52,   52,   52,   52,  506,  199,   52,   52,   52,   52,
       52,   52,  506,  506,  200,  202,   52,   52,   52,  506,
      203,   52,   52,   52,  201,  506,  506,  204,   52,   52,
       52,   52,   52,   52,   52,   52,   52,  206,   52,   52,
       52,  205,   52,   52,   52,  207,  506,  208,  506,  210,
       52,   52,   52,   52,   52,   52,   52,   52,   52,  506,

      506,  211,  209,   52,   52,   52,  506,  213,  506,  215,
      214,  506,  212,   52,   52,   52,   52,   52,   52,  506,
      506,  216,   52,   52,   52,   52,   52,   52,   52,   52,
       52,  506,  506,  217,   52,   52,   52,  506,  506,  219,
       52,   52,   52,  221,  506,  218,   52,   52,   52,  220,
       52,   52,   52,  224,  506,  506,  222,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  223,   52,   52,   52,
       52,   52,   52,  225,   52,   52,   52,  506,  506,  226,
      227,   52,   52,   52,   52,   52,   52,   52,   52,   52,
      230,  231,  228,   52,   52,   52,  229,  506,  237,  232,

      238,  238,  238,  506,  233,   52,   52,   52,   52,   52,
       52,  234,  235,  506,  239,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  506,  236,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  506,  240,
      506,  242,  241,  506,  506,  244,   52,   52,   52,  506,
      506,  243,  506,   52,   52,   52,   52,   52,   52,  506,
       52,   52,   52,   52,   52,   52,  506,  245,   52,   52,
       52,  246,  247,  249,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  506,  506,  248,   52,
       52,   52,   52,   52,   52,  506,  250,  251,  506,  253,

       52,   52,   52,   52,   52,   52,   52,   52,   52,  506,
      252,  259,  506,  506,  254,  506,  258,   52,   52,   52,
       52,  264,   52,  261,  506,  260,   52,   52,   52,   52,
       52,   52,  263,   52,   52,   52,   52,   52,   52,  262,
       52,   52,   52,  506,   52,   52,   52,  506,  506,  267,
      506,  265,   52,   52,   52,   52,   52,   52,   52,   52,
       52,  266,   52,   52,   52,  506,  506,  270,   52,   52,
       52,  506,  506,  268,  269,   52,   52,   52,  271,  506,
      506,  272,   52,   52,   52,   52,   52,   52,  506,  506,
      274,   52,   52,   52,  506,  506,  273,   52,   52,   52,

       52,   52,   52,  506,  506,  275,   52,   52,   52,   52,
       52,   52,   52,   52,   52,  506,   52,   52,   52,  506,
      506,  276,  280,  506,  506,  277,   52,   52,   52,   52,
       52,   52,  278,   52,   52,   52,  506,  506,  279,  282,
       52,   52,   52,   52,   52,   52,  281,  506,  284,   52,
       52,   52,  506,  283,   52,   52,   52,   52,   52,   52,
      286,   52,   52,   52,   52,   52,   52,  285,   52,   52,
       52,   52,   52,   52,  287,   52,   52,   52,  289,  238,
      238,  238,  506,  506,  290,  288,  238,  238,  238,  291,
      292,   52,   52,   52,  293,   52,   52,   52,   52,   52,

       52,  506,  294,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,  506,  295,   52,   52,   52,
       52,   52,   52,  506,   52,   52,   52,  298,  297,   52,
       52,   52,  506,   52,   52,   52,  299,  506,  296,  301,
       52,   52,   52,   52,   52,   52,   52,   52,   52,  300,
       52,   52,   52,  506,  302,  506,  506,  303,  304,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  305,  307,
       52,   52,   52,  506,  506,  306,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  506,  312,
      314,  506,  506,  311,  315,   52,   52,   52,  313,   52,

       52,   52,   52,   52,   52,  506,  506,  318,   52,   52,
       52,  316,   52,   52,   52,   52,   52,   52,  506,  321,
      506,   52,   52,   52,   52,   52,   52,  319,  320,  322,
       52,   52,   52,   52,   52,   52,  506,  506,   52,   52,
       52,  506,   52,   52,   52,  506,  324,  326,  506,  323,
      325,   52,   52,   52,  506,  506,  328,  329,   52,   52,
       52,  506,  327,  506,  330,  331,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  506,  333,  332,   52,   52,   52,
       52,   52,   52,  336,   52,   52,   52,  334,  506,  337,

      335,  506,  339,  338,   52,   52,   52,  506,  506,  342,
       52,   52,   52,  340,   52,   52,   52,   52,   52,   52,
       52,   52,   52,  341,   52,   52,   52,  506,  344,   52,
       52,   52,   52,   52,   52,  506,  506,  343,   52,   52,
       52,   52,   52,   52,  506,  345,   52,   52,   52,   52,
       52,   52,  506,  506,  346,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
      350,   52,   52,   52,  506,  506,  349,  347,  348,   52,
       52,   52,  351,   52,   52,   52,   52,   52,   52,  506,
      506,  353,  506,  352,   52,   52,   52,   52,   52,   52,

      506,  358,  506,  354,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  360,  506,   52,   52,
       52,  506,  359,   52,   52,   52,   52,   52,   52,   52,
       52,   52,  361,  364,   52,   52,   52,   52,   52,   52,
      506,  506,  365,   52,   52,   52,  506,  363,   52,   52,
       52,   52,   52,   52,   52,   52,   52,  506,   52,   52,
       52,  366,  368,   52,   52,   52,  369,   52,   52,   52,
      506,  367,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  506,  370,  372,  371,  506,  506,
      373,   52,   52,   52,  376,  375,   52,   52,   52,  374,

       52,   52,   52,   52,   52,   52,   52,   52,   52,  506,
       52,   52,   52,   52,   52,   52,   52,   52,   52,  378,
       52,   52,   52,   52,   52,   52,  506,  506,  377,  381,
       52,   52,   52,  379,  506,  506,  384,  380,   52,   52,
       52,  506,  382,  385,  506,  383,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,  506,  388,  387,
      386,   52,   52,   52,   52,   52,   52,  506,  506,  393,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,  506,  392,   52,   52,   52,   52,   52,   52,

       52,   52,   52,  506,  394,   52,   52,   52,  506,  396,
       52,   52,   52,  506,  397,   52,   52,   52,  506,  398,
       52,   52,   52,  506,  399,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  506,  400,  506,  506,  403,   52,
       52,   52,  401,  404,  506,  402,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  406,   52,
       52,   52,  506,  405,   52,   52,   52,   52,   52,   52,
       52,   52,   52,  407,   52,   52,   52,  408,  409,   52,
       52,   52,  506,  410,  411,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,  412,   52,   52,

       52,   52,   52,   52,  506,  506,  413,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  414,  420,  506,  506,
      421,  506,  506,  418,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  506,  422,   52,   52,
       52,   52,   52,   52,  506,  423,   52,   52,   52,   52,
       52,   52,  506,  506,  428,  506,  426,  506,  506,  425,
       52,   52,   52,  506,  424,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  506,  427,  506,  506,  429,   52,
       52,   52,  506,   52,   52,   52,   52,   52,   52,  506,
      506,  430,   52,   52,   52,  506,  431,  506,  506,  432,

       52,   52,   52,   52,   52,   52,   52,   52,   52,  506,
      506,  433,  434,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  506,  439,
      506,  440,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  441,   52,   52,   52,   52,   52,
       52,  442,  443,   52,   52,   52,  445,   52,   52,   52,
      506,  446,   52,   52,   52,  506,  444,  447,   52,   52,
       52,   52,   52,   52,  506,  453,  506,   52,   52,   52,
      506,  506,  452,   52,   52,   52,  506,  454,   52,   52,
       52,   52,   52,   52,   52,   52,   52,  506,  506,  455,

      456,  506,  457,  458,   52,   52,   52,  506,  459,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  506,  463,
      506,  506,  464,   52,   52,   52,   52,   52,   52,   52,
       52,   52,  465,  506,   52,   52,   52,   52,   52,   52,
      506,  506,  466,   52,   52,   52,   52,   52,   52,  468,
      506,  506,  469,  473,  506,  467,  506,  506,  475,  506,
      474,   52,   52,   52,   52,   52,   52,  476,   52,   52,
       52,   52,   52,   52,  506,  506,  477,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  506,  506,  479,  478,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,

       52,   52,  506,  484,  483,  506,  485,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,  486,
      490,   52,   52,   52,   52,   52,   52,   52,   52,   52,
      493,  506,  491,  506,  506,  492,   52,   52,   52,  506,
      506,  506,  506,  497,    3,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506

    } ;

static grib_yyconst flex_int16_t grib_yy_chk[2096] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       11,   11,   11,   12,   12,   12,   12,   13,   13,   16,
       16,   16,   17,   17,   17,   18,   18,   18,   20,   20,
       20,   17,  508,   21,   21,   21,   22,   22,   22,   23,
       23,   23,  507,   25,  504,   25,  503,   25,   18,   25,
      501,   22,  500,   20,  498,   20,   21,   20,   23,   20,

       24,   21,  496,  495,   22,  494,  489,   24,  488,   24,
       21,   24,   23,   24,   26,   26,   26,  487,   24,   27,
       27,   27,   29,  482,   29,  481,   29,  480,   29,   45,
       45,   45,   45,   26,   30,   30,   30,   31,   46,   46,
       46,   31,   27,   28,  472,   31,   28,   28,  471,   30,
       31,  470,   28,   30,   28,  462,   28,   30,   28,   28,
       32,  461,   30,  460,   32,   33,   33,   33,   32,  450,
      449,   34,   35,   32,  448,   34,   35,  438,   32,   34,
       35,  437,  436,   36,   34,   35,   34,   36,  435,   37,
      419,   36,   36,   37,  417,   33,   36,   37,  416,   33,

       36,  415,   37,   36,   37,   38,   38,   38,   39,   39,
       39,   47,   47,   47,   47,   53,   53,   53,  395,   54,
       54,   54,   55,   55,   55,   56,   56,   56,  391,  390,
       39,   54,   38,   57,   57,   57,  389,  362,   39,   58,
       58,   58,   55,   59,   59,   59,  357,  356,   56,  355,
      317,   57,   60,   60,   60,   61,   61,   61,  310,  309,
       59,   62,   62,   62,  308,   63,  264,   63,   58,   63,
       64,   63,  257,  256,   59,  255,  195,   64,   64,   64,
      194,   64,  193,   64,   60,   65,   65,   65,   66,   66,
       66,   61,   72,   62,   67,   67,   67,   68,   68,   68,

       69,   69,   69,   42,   40,   65,   70,   70,   70,   71,
       71,   71,   15,   14,   66,   10,    7,   67,   69,   73,
       73,   73,    5,    3,   71,   74,   74,   74,   68,   75,
       75,   75,   77,   77,   77,   70,    0,   76,   76,   76,
       78,   78,   78,   74,   79,   79,   79,   80,   80,   80,
        0,   73,   81,   81,   81,   75,   76,   78,   82,   82,
       82,   83,   83,   83,    0,    0,   80,   84,   84,   84,
        0,   81,    0,    0,   82,   85,   85,   85,    0,    0,
       86,   86,   86,   87,   87,   87,    0,    0,   83,   88,
       88,   88,   89,   89,   89,   90,   90,   90,   84,    0,

        0,   87,   85,   85,   88,   89,   91,   91,   91,    0,
       85,   86,   86,   92,   92,   92,   93,   93,   93,    0,
       90,   94,   94,   94,   89,   95,   95,   95,   96,   96,
       96,    0,   92,    0,   93,    0,   97,   97,   97,   98,
       98,   98,    0,   96,   99,   99,   99,    0,   95,  100,
      100,  100,   94,   97,   96,  101,  101,  101,    0,    0,
       98,  102,  102,  102,  108,  108,  108,   99,   97,  103,
        0,  108,  104,  103,    0,    0,  104,  103,  101,  100,
      104,    0,  103,  108,    0,  104,  105,  102,  104,  106,
      105,  132,    0,  106,  105,  132,    0,  106,    0,  105,

      132,    0,  106,  109,  109,  109,  110,  110,  110,  111,
      111,  111,  112,  112,  112,  109,  113,  113,  113,  114,
      114,  114,    0,    0,  111,  115,  115,  115,  116,  116,
      116,  117,  117,  117,    0,  113,  118,  118,  118,  119,
      119,  119,  114,    0,  115,  120,  120,  120,  121,  121,
      121,    0,  119,    0,    0,  118,  122,  122,  122,  123,
      123,  123,    0,    0,  120,    0,    0,  121,  124,  124,
      124,  125,  125,  125,    0,    0,  123,  126,  126,  126,
      127,  127,  127,    0,    0,  122,  125,  129,  129,  129,
      123,  128,  128,  128,  130,  130,  130,  131,  131,  131,

      133,  133,  133,    0,    0,  124,  126,  134,  134,  134,
      128,    0,  127,  135,  135,  135,    0,    0,  131,  133,
        0,    0,  130,    0,    0,  134,  136,  136,  136,  137,
      137,  137,    0,  135,  138,  138,  138,    0,  139,  139,
      139,  140,  140,  140,    0,  136,  141,  141,  141,  142,
      142,  142,    0,    0,  137,  139,  143,  143,  143,    0,
      140,  144,  144,  144,  138,    0,    0,  141,  145,  145,
      145,  146,  146,  146,  147,  147,  147,  143,  148,  148,
      148,  142,  149,  149,  149,  144,    0,  145,    0,  147,
      150,  150,  150,  151,  151,  151,  152,  152,  152,    0,

        0,  148,  146,  153,  153,  153,    0,  150,    0,  151,
      150,    0,  149,  154,  154,  154,  155,  155,  155,    0,
        0,  152,  156,  156,  156,  157,  157,  157,  158,  158,
      158,    0,    0,  153,  159,  159,  159,    0,    0,  155,
      160,  160,  160,  157,    0,  154,  161,  161,  161,  156,
      162,  162,  162,  160,    0,    0,  158,  163,  163,  163,
      164,  164,  164,  166,  166,  166,  159,  165,  165,  165,
      167,  167,  167,  161,  168,  168,  168,    0,    0,  162,
      163,  169,  169,  169,  170,  170,  170,  171,  171,  171,
      166,  167,  164,  172,  172,  172,  165,    0,  173,  168,

      173,  173,  173,    0,  169,  174,  174,  174,  175,  175,
      175,  170,  171,    0,  174,  176,  176,  176,  177,  177,
      177,  178,  178,  178,    0,  172,  179,  179,  179,  180,
      180,  180,  181,  181,  181,  182,  182,  182,    0,  175,
        0,  177,  176,    0,    0,  180,  183,  183,  183,    0,
        0,  178,    0,  184,  184,  184,  185,  185,  185,    0,
      186,  186,  186,  187,  187,  187,    0,  182,  188,  188,
      188,  183,  184,  186,  189,  189,  189,  190,  190,  190,
      191,  191,  191,  192,  192,  192,    0,    0,  185,  196,
      196,  196,  197,  197,  197,    0,  187,  189,    0,  192,

      198,  198,  198,  199,  199,  199,  200,  200,  200,    0,
      191,  197,    0,    0,  192,    0,  196,  201,  201,  201,
      202,  202,  202,  199,    0,  198,  203,  203,  203,  204,
      204,  204,  201,  205,  205,  205,  206,  206,  206,  200,
      207,  207,  207,    0,  208,  208,  208,    0,    0,  206,
        0,  203,  209,  209,  209,  210,  210,  210,  211,  211,
      211,  204,  212,  212,  212,    0,    0,  209,  213,  213,
      213,    0,    0,  207,  208,  214,  214,  214,  211,    0,
        0,  212,  215,  215,  215,  216,  216,  216,    0,    0,
      214,  217,  217,  217,    0,    0,  213,  218,  218,  218,

      219,  219,  219,    0,    0,  215,  220,  220,  220,  221,
      221,  221,  222,  222,  222,    0,  223,  223,  223,    0,
        0,  217,  221,    0,    0,  218,  224,  224,  224,  225,
      225,  225,  219,  226,  226,  226,    0,    0,  220,  223,
      227,  227,  227,  228,  228,  228,  222,    0,  225,  229,
      229,  229,    0,  224,  230,  230,  230,  231,  231,  231,
      228,  232,  232,  232,  234,  234,  234,  227,  233,  233,
      233,  235,  235,  235,  229,  236,  236,  236,  231,  237,
      237,  237,    0,    0,  232,  230,  238,  238,  238,  233,
      235,  239,  239,  239,  236,  240,  240,  240,  241,  241,

      241,    0,  239,  242,  242,  242,  243,  243,  243,  244,
      244,  244,  245,  245,  245,    0,  241,  246,  246,  246,
      247,  247,  247,    0,  248,  248,  248,  245,  244,  249,
      249,  249,    0,  250,  250,  250,  246,    0,  243,  248,
      251,  251,  251,  252,  252,  252,  253,  253,  253,  247,
      254,  254,  254,    0,  248,    0,    0,  249,  250,  258,
      258,  258,  259,  259,  259,  261,  261,  261,  251,  253,
      260,  260,  260,    0,    0,  252,  262,  262,  262,  263,
      263,  263,  265,  265,  265,  266,  266,  266,    0,  259,
      261,    0,    0,  258,  262,  267,  267,  267,  260,  268,

      268,  268,  269,  269,  269,    0,    0,  266,  270,  270,
      270,  263,  271,  271,  271,  272,  272,  272,    0,  269,
        0,  273,  273,  273,  274,  274,  274,  267,  268,  270,
      275,  275,  275,  276,  276,  276,    0,    0,  277,  277,
      277,    0,  278,  278,  278,    0,  272,  274,    0,  271,
      273,  279,  279,  279,    0,    0,  276,  277,  280,  280,
      280,    0,  275,    0,  277,  278,  281,  281,  281,  282,
      282,  282,  283,  283,  283,  284,  284,  284,  285,  285,
      285,  286,  286,  286,    0,  281,  280,  287,  287,  287,
      288,  288,  288,  284,  290,  290,  290,  282,    0,  285,

      283,    0,  287,  286,  289,  289,  289,    0,    0,  290,
      291,  291,  291,  288,  292,  292,  292,  293,  293,  293,
      294,  294,  294,  289,  295,  295,  295,    0,  294,  296,
      296,  296,  297,  297,  297,    0,    0,  291,  298,  298,
      298,  299,  299,  299,    0,  297,  300,  300,  300,  301,
      301,  301,    0,    0,  298,  302,  302,  302,  303,  303,
      303,  304,  304,  304,  305,  305,  305,  306,  306,  306,
      302,  307,  307,  307,    0,    0,  301,  299,  300,  311,
      311,  311,  303,  312,  312,  312,  313,  313,  313,    0,
        0,  305,    0,  304,  314,  314,  314,  315,  315,  315,

        0,  313,    0,  307,  316,  316,  316,  318,  318,  318,
      319,  319,  319,  320,  320,  320,  315,    0,  321,  321,
      321,    0,  314,  322,  322,  322,  323,  323,  323,  324,
      324,  324,  316,  321,  325,  325,  325,  326,  326,  326,
        0,    0,  322,  327,  327,  327,    0,  319,  328,  328,
      328,  329,  329,  329,  330,  330,  330,    0,  331,  331,
      331,  324,  326,  332,  332,  332,  328,  333,  333,  333,
        0,  325,  334,  334,  334,  335,  335,  335,  336,  336,
      336,  337,  337,  337,    0,  329,  331,  330,    0,    0,
      332,  338,  338,  338,  337,  335,  339,  339,  339,  334,

      340,  340,  340,  341,  341,  341,  342,  342,  342,    0,
      343,  343,  343,  344,  344,  344,  345,  345,  345,  340,
      346,  346,  346,  347,  347,  347,    0,    0,  339,  343,
      348,  348,  348,  341,    0,    0,  347,  342,  349,  349,
      349,    0,  345,  348,    0,  346,  350,  350,  350,  351,
      351,  351,  352,  352,  352,  353,  353,  353,  354,  354,
      354,  358,  358,  358,  359,  359,  359,    0,  353,  350,
      349,  360,  360,  360,  361,  361,  361,    0,    0,  359,
      363,  363,  363,  364,  364,  364,  365,  365,  365,  366,
      366,  366,    0,  358,  367,  367,  367,  368,  368,  368,

      369,  369,  369,    0,  361,  370,  370,  370,    0,  363,
      371,  371,  371,    0,  364,  372,  372,  372,    0,  369,
      373,  373,  373,    0,  370,  374,  374,  374,  375,  375,
      375,  376,  376,  376,    0,  371,    0,    0,  374,  377,
      377,  377,  372,  375,    0,  373,  378,  378,  378,  379,
      379,  379,  380,  380,  380,  382,  382,  382,  377,  381,
      381,  381,    0,  376,  383,  383,  383,  384,  384,  384,
      385,  385,  385,  378,  386,  386,  386,  381,  382,  387,
      387,  387,    0,  383,  384,  388,  388,  388,  392,  392,
      392,  393,  393,  393,  394,  394,  394,  385,  396,  396,

      396,  397,  397,  397,    0,    0,  387,  398,  398,  398,
      399,  399,  399,  400,  400,  400,  388,  396,    0,    0,
      397,    0,    0,  393,  401,  401,  401,  402,  402,  402,
      403,  403,  403,  404,  404,  404,    0,  399,  405,  405,
      405,  406,  406,  406,    0,  400,  407,  407,  407,  408,
      408,  408,    0,    0,  406,    0,  404,    0,    0,  403,
      409,  409,  409,    0,  402,  410,  410,  410,  411,  411,
      411,  412,  412,  412,    0,  405,    0,    0,  407,  413,
      413,  413,    0,  414,  414,  414,  418,  418,  418,    0,
        0,  409,  420,  420,  420,    0,  411,    0,    0,  412,

      421,  421,  421,  422,  422,  422,  423,  423,  423,    0,
        0,  413,  414,  424,  424,  424,  425,  425,  425,  426,
      426,  426,  427,  427,  427,  428,  428,  428,    0,  423,
        0,  425,  429,  429,  429,  430,  430,  430,  431,  431,
      431,  432,  432,  432,  426,  433,  433,  433,  434,  434,
      434,  427,  428,  439,  439,  439,  431,  440,  440,  440,
        0,  432,  441,  441,  441,    0,  430,  434,  442,  442,
      442,  443,  443,  443,    0,  440,    0,  444,  444,  444,
        0,    0,  439,  445,  445,  445,    0,  442,  446,  446,
      446,  447,  447,  447,  452,  452,  452,    0,    0,  443,

      444,    0,  445,  446,  453,  453,  453,    0,  447,  454,
      454,  454,  455,  455,  455,  456,  456,  456,    0,  452,
        0,    0,  453,  457,  457,  457,  458,  458,  458,  459,
      459,  459,  455,    0,  463,  463,  463,  464,  464,  464,
        0,    0,  456,  465,  465,  465,  466,  466,  466,  458,
        0,    0,  459,  463,    0,  457,    0,    0,  465,    0,
      464,  467,  467,  467,  468,  468,  468,  466,  469,  469,
      469,  473,  473,  473,    0,    0,  467,  474,  474,  474,
      475,  475,  475,  476,  476,  476,    0,    0,  469,  468,
      477,  477,  477,  478,  478,  478,  479,  479,  479,  483,

      483,  483,    0,  475,  474,    0,  477,  484,  484,  484,
      485,  485,  485,  486,  486,  486,  490,  490,  490,  479,
      483,  491,  491,  491,  492,  492,  492,  493,  493,  493,
      486,    0,  484,    0,    0,  485,  497,  497,  497,    0,
        0,    0,    0,  492,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506

    } ;

static grib_yy_state_type grib_yy_last_accepting_state;
static char *grib_yy_last_accepting_cpos;

extern int grib_yy_flex_debug;
int grib_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define grib_yymore() grib_yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *grib_yytext;
#line 1 "gribl.l"
/*
 * Copyright 2005-2014 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * In applying this licence, ECMWF does not waive the privileges and immunities granted to it by
 * virtue of its status as an intergovernmental organisation nor does it submit to any jurisdiction.
 */
#line 13 "gribl.l"
#include "grib_api_internal.h"
#include "grib_yacc.h"
#include <ctype.h>

int grib_yylineno;

/* Keep -Wall quiet */


/*

This is needed for implementing "include", otherwise
flex buffer optimization break the includes.

*/

#define YY_INPUT(buf,result,max_size) \
        { \
        int c = getc(grib_yyin); \
        result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
        }


/*
#ifdef __GNUC__
#ifdef FLEX_SCANNER
void grib_yyunput (int c,char *buf_ptr  );
void _grib_ignore_grib_yyunput_unused_error() { grib_yyunput(0,0); }
#endif
#endif
*/

#line 1120 "lex.grib_yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int grib_yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int grib_yylex_destroy (void );

int grib_yyget_debug (void );

void grib_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE grib_yyget_extra (void );

void grib_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *grib_yyget_in (void );

void grib_yyset_in  (FILE * in_str  );

FILE *grib_yyget_out (void );

void grib_yyset_out  (FILE * out_str  );

int grib_yyget_leng (void );

char *grib_yyget_text (void );

int grib_yyget_lineno (void );

void grib_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int grib_yywrap (void );
#else
extern int grib_yywrap (void );
#endif
#endif

    void grib_yyunput (int c,char *buf_ptr  );
    
#ifndef grib_yytext_ptr
static void grib_yy_flex_strncpy (char *,grib_yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int grib_yy_flex_strlen (grib_yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int grib_yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( grib_yytext, grib_yyleng, 1, grib_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( grib_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( grib_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, grib_yyin))==0 && ferror(grib_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(grib_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "grib_yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef grib_yyterminate
#define grib_yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) grib_yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int grib_yylex (void);

#define YY_DECL int grib_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after grib_yytext and grib_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register grib_yy_state_type grib_yy_current_state;
	register char *grib_yy_cp, *grib_yy_bp;
	register int grib_yy_act;
    
#line 57 "gribl.l"



#line 1306 "lex.grib_yy.c"

	if ( !(grib_yy_init) )
		{
		(grib_yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (grib_yy_start) )
			(grib_yy_start) = 1;	/* first start state */

		if ( ! grib_yyin )
			grib_yyin = stdin;

		if ( ! grib_yyout )
			grib_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			grib_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE );
		}

		grib_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		grib_yy_cp = (grib_yy_c_buf_p);

		/* Support of grib_yytext. */
		*grib_yy_cp = (grib_yy_hold_char);

		/* grib_yy_bp points to the position in grib_yy_ch_buf of the start of
		 * the current run.
		 */
		grib_yy_bp = grib_yy_cp;

		grib_yy_current_state = (grib_yy_start);
grib_yy_match:
		do
			{
			register YY_CHAR grib_yy_c = grib_yy_ec[YY_SC_TO_UI(*grib_yy_cp)];
			if ( grib_yy_accept[grib_yy_current_state] )
				{
				(grib_yy_last_accepting_state) = grib_yy_current_state;
				(grib_yy_last_accepting_cpos) = grib_yy_cp;
				}
			while ( grib_yy_chk[grib_yy_base[grib_yy_current_state] + grib_yy_c] != grib_yy_current_state )
				{
				grib_yy_current_state = (int) grib_yy_def[grib_yy_current_state];
				if ( grib_yy_current_state >= 507 )
					grib_yy_c = grib_yy_meta[(unsigned int) grib_yy_c];
				}
			grib_yy_current_state = grib_yy_nxt[grib_yy_base[grib_yy_current_state] + (unsigned int) grib_yy_c];
			++grib_yy_cp;
			}
		while ( grib_yy_base[grib_yy_current_state] != 2045 );

grib_yy_find_action:
		grib_yy_act = grib_yy_accept[grib_yy_current_state];
		if ( grib_yy_act == 0 )
			{ /* have to back up */
			grib_yy_cp = (grib_yy_last_accepting_cpos);
			grib_yy_current_state = (grib_yy_last_accepting_state);
			grib_yy_act = grib_yy_accept[grib_yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( grib_yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*grib_yy_cp = (grib_yy_hold_char);
			grib_yy_cp = (grib_yy_last_accepting_cpos);
			grib_yy_current_state = (grib_yy_last_accepting_state);
			goto grib_yy_find_action;

case 1:
YY_RULE_SETUP
#line 60 "gribl.l"
return EQ       ;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 61 "gribl.l"
return GE       ;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 62 "gribl.l"
return GT       ;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 63 "gribl.l"
return LE       ;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "gribl.l"
return LT       ;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 65 "gribl.l"
return NE       ;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 "gribl.l"
return NE       ;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 67 "gribl.l"
return BIT      ;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 "gribl.l"
return BITOFF   ;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "gribl.l"
return IS   ;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "gribl.l"
return NOT   ;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "gribl.l"
return NOT   ;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "gribl.l"
return AND   ;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "gribl.l"
return AND   ;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "gribl.l"
return OR   ;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "gribl.l"
return OR   ;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 78 "gribl.l"
return NIL   ;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 79 "gribl.l"
return DUMMY   ;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "gribl.l"
return LOWERCASE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "gribl.l"
return IF       ;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "gribl.l"
return IF_TRANSIENT       ;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "gribl.l"
return ELSE       ;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "gribl.l"
return UNSIGNED ;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "gribl.l"
return ASCII    ;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "gribl.l"
return BYTE    ;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "gribl.l"
return LABEL    ;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "gribl.l"
return LIST     ;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "gribl.l"
return WHILE     ;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "gribl.l"
return TEMPLATE ;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "gribl.l"
return TEMPLATE_NOFAIL ;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "gribl.l"
return TRIGGER ;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "gribl.l"
return END      ;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "gribl.l"
return IBMFLOAT ;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "gribl.l"
return FLOAT ;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "gribl.l"
return SIGNED   ;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "gribl.l"
return CODETABLE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "gribl.l"
return GETENV;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "gribl.l"
return CODETABLE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "gribl.l"
return FLAG     ;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "gribl.l"
return LOOKUP   ;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "gribl.l"
return META     ;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "gribl.l"
return PADTOEVEN    ;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "gribl.l"
return PADTO    ;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "gribl.l"
return PADTOMULTIPLE    ;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "gribl.l"
return PAD      ;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 "gribl.l"
return SECTION_PADDING      ;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 "gribl.l"
return MESSAGE      ;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "gribl.l"
return ALIAS    ;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "gribl.l"
return UNALIAS    ;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 "gribl.l"
return POS      ;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 "gribl.l"
return INTCONST ;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 "gribl.l"
return TRANS    ;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 115 "gribl.l"
return STRING_TYPE   ;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "gribl.l"
return LONG_TYPE   ;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "gribl.l"
return ITERATOR ;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "gribl.l"
return NEAREST ;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 119 "gribl.l"
return BOX ;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 120 "gribl.l"
return KSEC    ;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 121 "gribl.l"
return FLAGBIT    ;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 122 "gribl.l"
return KSEC1EXPVER    ;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 123 "gribl.l"
return MODIFY    ;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 125 "gribl.l"
return G1_HALF_BYTE    ;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 126 "gribl.l"
return G1_MESSAGE_LENGTH    ;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 127 "gribl.l"
return G1_SECTION4_LENGTH    ;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 129 "gribl.l"
return EXPORT;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 130 "gribl.l"
return REMOVE;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 132 "gribl.l"
return SECTION_LENGTH     ;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 134 "gribl.l"
return ASSERT    ;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 136 "gribl.l"
return READ_ONLY;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 137 "gribl.l"
return NO_COPY;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 138 "gribl.l"
return EDITION_SPECIFIC;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 139 "gribl.l"
return DUMP;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 140 "gribl.l"
return NO_FAIL;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 141 "gribl.l"
return HIDDEN;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 142 "gribl.l"
return CAN_BE_MISSING;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 143 "gribl.l"
return MISSING;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 144 "gribl.l"
return CONSTRAINT;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 145 "gribl.l"
return OVERRIDE;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 146 "gribl.l"
return COPY_OK;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 148 "gribl.l"
return SET;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 149 "gribl.l"
return SET_NOFAIL;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 150 "gribl.l"
return WHEN;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 151 "gribl.l"
return CASE;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 152 "gribl.l"
return SWITCH;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 153 "gribl.l"
return DEFAULT;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 154 "gribl.l"
return CONCEPT;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 155 "gribl.l"
return CONCEPT_NOFAIL;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 156 "gribl.l"
return WRITE;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 157 "gribl.l"
return APPEND;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 158 "gribl.l"
return PRINT;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 159 "gribl.l"
return SKIP;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 161 "gribl.l"
{
          int c,q;
          while((c = input()) && isspace(c) && c != '\n') ;
          q = c; /* the quote */

          grib_yyleng = 0;
          while((c = input()) && c != q && c != '\n')
                {
                    if(c == '\\') grib_yytext[grib_yyleng++] = input();
                    else grib_yytext[grib_yyleng++] =  c;
                }

                grib_yytext[grib_yyleng++] = 0;

          grib_parser_include(grib_yytext);
         }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 178 "gribl.l"
{
           int c,q = grib_yytext[0];

           grib_yyleng = 0;

           while((c = input()) && c != q && c != '\n')
           {
               if(c == '\\') grib_yytext[grib_yyleng++] = input();
               else grib_yytext[grib_yyleng++] =  c;
            }

            grib_yytext[grib_yyleng++] = 0;
            grib_yylval.str = strdup(grib_yytext);
            return STRING;
        }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 194 "gribl.l"
{
           int c;
           unsigned long val = 0;

           while((c = input()) && c != '`' && c != '\n')
           {
                val <<= 8;
                val |= c;
           }
           grib_yylval.lval = val;
           return INTEGER;
        }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 208 "gribl.l"
{ grib_yylval.str = strdup(grib_yytext); return IDENT; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 209 "gribl.l"
{ grib_yylval.lval = atol((const char *)grib_yytext); return INTEGER; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 210 "gribl.l"
{ grib_yylval.dval = atof((const char *)grib_yytext); return FLOAT; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 213 "gribl.l"
{
           int c;
           while((c = input()) && (c != '\n')){}

        grib_yylineno++;
        }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 219 "gribl.l"
;
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 220 "gribl.l"
grib_yylineno++;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 224 "gribl.l"
return *grib_yytext;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 226 "gribl.l"
ECHO;
	YY_BREAK
#line 1945 "lex.grib_yy.c"
case YY_STATE_EOF(INITIAL):
	grib_yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int grib_yy_amount_of_matched_text = (int) (grib_yy_cp - (grib_yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*grib_yy_cp = (grib_yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed grib_yyin at a new source and called
			 * grib_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(grib_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->grib_yy_input_file = grib_yyin;
			YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for grib_yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since grib_yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (grib_yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)] )
			{ /* This was really a NUL. */
			grib_yy_state_type grib_yy_next_state;

			(grib_yy_c_buf_p) = (grib_yytext_ptr) + grib_yy_amount_of_matched_text;

			grib_yy_current_state = grib_yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * grib_yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			grib_yy_next_state = grib_yy_try_NUL_trans( grib_yy_current_state );

			grib_yy_bp = (grib_yytext_ptr) + YY_MORE_ADJ;

			if ( grib_yy_next_state )
				{
				/* Consume the NUL. */
				grib_yy_cp = ++(grib_yy_c_buf_p);
				grib_yy_current_state = grib_yy_next_state;
				goto grib_yy_match;
				}

			else
				{
				grib_yy_cp = (grib_yy_c_buf_p);
				goto grib_yy_find_action;
				}
			}

		else switch ( grib_yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(grib_yy_did_buffer_switch_on_eof) = 0;

				if ( grib_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * grib_yy_get_next_buffer() to have set up
					 * grib_yytext, we can now set up
					 * grib_yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(grib_yy_c_buf_p) = (grib_yytext_ptr) + YY_MORE_ADJ;

					grib_yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (grib_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(grib_yy_c_buf_p) =
					(grib_yytext_ptr) + grib_yy_amount_of_matched_text;

				grib_yy_current_state = grib_yy_get_previous_state(  );

				grib_yy_cp = (grib_yy_c_buf_p);
				grib_yy_bp = (grib_yytext_ptr) + YY_MORE_ADJ;
				goto grib_yy_match;

			case EOB_ACT_LAST_MATCH:
				(grib_yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)];

				grib_yy_current_state = grib_yy_get_previous_state(  );

				grib_yy_cp = (grib_yy_c_buf_p);
				grib_yy_bp = (grib_yytext_ptr) + YY_MORE_ADJ;
				goto grib_yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of grib_yylex */

/* grib_yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int grib_yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf;
	register char *source = (grib_yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (grib_yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (grib_yy_c_buf_p) - (grib_yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((grib_yy_c_buf_p) - (grib_yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int grib_yy_c_buf_p_offset =
				(int) ((grib_yy_c_buf_p) - b->grib_yy_ch_buf);

			if ( b->grib_yy_is_our_buffer )
				{
				int new_size = b->grib_yy_buf_size * 2;

				if ( new_size <= 0 )
					b->grib_yy_buf_size += b->grib_yy_buf_size / 8;
				else
					b->grib_yy_buf_size *= 2;

				b->grib_yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					grib_yyrealloc((void *) b->grib_yy_ch_buf,b->grib_yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->grib_yy_ch_buf = 0;

			if ( ! b->grib_yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(grib_yy_c_buf_p) = &b->grib_yy_ch_buf[grib_yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[number_to_move]),
			(grib_yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars);
		}

	if ( (grib_yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			grib_yyrestart(grib_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((grib_yy_size_t) ((grib_yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		grib_yy_size_t new_size = (grib_yy_n_chars) + number_to_move + ((grib_yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf = (char *) grib_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in grib_yy_get_next_buffer()" );
	}

	(grib_yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(grib_yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[0];

	return ret_val;
}

/* grib_yy_get_previous_state - get the state just before the EOB char was reached */

    static grib_yy_state_type grib_yy_get_previous_state (void)
{
	register grib_yy_state_type grib_yy_current_state;
	register char *grib_yy_cp;
    
	grib_yy_current_state = (grib_yy_start);

	for ( grib_yy_cp = (grib_yytext_ptr) + YY_MORE_ADJ; grib_yy_cp < (grib_yy_c_buf_p); ++grib_yy_cp )
		{
		register YY_CHAR grib_yy_c = (*grib_yy_cp ? grib_yy_ec[YY_SC_TO_UI(*grib_yy_cp)] : 1);
		if ( grib_yy_accept[grib_yy_current_state] )
			{
			(grib_yy_last_accepting_state) = grib_yy_current_state;
			(grib_yy_last_accepting_cpos) = grib_yy_cp;
			}
		while ( grib_yy_chk[grib_yy_base[grib_yy_current_state] + grib_yy_c] != grib_yy_current_state )
			{
			grib_yy_current_state = (int) grib_yy_def[grib_yy_current_state];
			if ( grib_yy_current_state >= 507 )
				grib_yy_c = grib_yy_meta[(unsigned int) grib_yy_c];
			}
		grib_yy_current_state = grib_yy_nxt[grib_yy_base[grib_yy_current_state] + (unsigned int) grib_yy_c];
		}

	return grib_yy_current_state;
}

/* grib_yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = grib_yy_try_NUL_trans( current_state );
 */
    static grib_yy_state_type grib_yy_try_NUL_trans  (grib_yy_state_type grib_yy_current_state )
{
	register int grib_yy_is_jam;
    	register char *grib_yy_cp = (grib_yy_c_buf_p);

	register YY_CHAR grib_yy_c = 1;
	if ( grib_yy_accept[grib_yy_current_state] )
		{
		(grib_yy_last_accepting_state) = grib_yy_current_state;
		(grib_yy_last_accepting_cpos) = grib_yy_cp;
		}
	while ( grib_yy_chk[grib_yy_base[grib_yy_current_state] + grib_yy_c] != grib_yy_current_state )
		{
		grib_yy_current_state = (int) grib_yy_def[grib_yy_current_state];
		if ( grib_yy_current_state >= 507 )
			grib_yy_c = grib_yy_meta[(unsigned int) grib_yy_c];
		}
	grib_yy_current_state = grib_yy_nxt[grib_yy_base[grib_yy_current_state] + (unsigned int) grib_yy_c];
	grib_yy_is_jam = (grib_yy_current_state == 506);

	return grib_yy_is_jam ? 0 : grib_yy_current_state;
}

    void grib_yyunput (int c, register char * grib_yy_bp )
{
	register char *grib_yy_cp;
    
    grib_yy_cp = (grib_yy_c_buf_p);

	/* undo effects of setting up grib_yytext */
	*grib_yy_cp = (grib_yy_hold_char);

	if ( grib_yy_cp < YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (grib_yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf )
			*--dest = *--source;

		grib_yy_cp += (int) (dest - source);
		grib_yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars =
			(grib_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size;

		if ( grib_yy_cp < YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--grib_yy_cp = (char) c;

	(grib_yytext_ptr) = grib_yy_bp;
	(grib_yy_hold_char) = *grib_yy_cp;
	(grib_yy_c_buf_p) = grib_yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int grib_yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(grib_yy_c_buf_p) = (grib_yy_hold_char);

	if ( *(grib_yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* grib_yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (grib_yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)] )
			/* This was really a NUL. */
			*(grib_yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (grib_yy_c_buf_p) - (grib_yytext_ptr);
			++(grib_yy_c_buf_p);

			switch ( grib_yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because grib_yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					grib_yyrestart(grib_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( grib_yywrap( ) )
						return EOF;

					if ( ! (grib_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return grib_yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(grib_yy_c_buf_p) = (grib_yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (grib_yy_c_buf_p);	/* cast for 8-bit char's */
	*(grib_yy_c_buf_p) = '\0';	/* preserve grib_yytext */
	(grib_yy_hold_char) = *++(grib_yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void grib_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        grib_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE );
	}

	grib_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	grib_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void grib_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		grib_yypop_buffer_state();
	 *		grib_yypush_buffer_state(new_buffer);
     */
	grib_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(grib_yy_c_buf_p) = (grib_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_pos = (grib_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	grib_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (grib_yywrap()) processing, but the only time this flag
	 * is looked at is after grib_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(grib_yy_did_buffer_switch_on_eof) = 1;
}

static void grib_yy_load_buffer_state  (void)
{
    	(grib_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars;
	(grib_yytext_ptr) = (grib_yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_pos;
	grib_yyin = YY_CURRENT_BUFFER_LVALUE->grib_yy_input_file;
	(grib_yy_hold_char) = *(grib_yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE grib_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) grib_yyalloc(sizeof( struct grib_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_create_buffer()" );

	b->grib_yy_buf_size = size;

	/* grib_yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->grib_yy_ch_buf = (char *) grib_yyalloc(b->grib_yy_buf_size + 2  );
	if ( ! b->grib_yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_create_buffer()" );

	b->grib_yy_is_our_buffer = 1;

	grib_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with grib_yy_create_buffer()
 * 
 */
    void grib_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->grib_yy_is_our_buffer )
		grib_yyfree((void *) b->grib_yy_ch_buf  );

	grib_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a grib_yyrestart() or at EOF.
 */
    static void grib_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	grib_yy_flush_buffer(b );

	b->grib_yy_input_file = file;
	b->grib_yy_fill_buffer = 1;

    /* If b is the current buffer, then grib_yy_init_buffer was _probably_
     * called from grib_yyrestart() or through grib_yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->grib_yy_bs_lineno = 1;
        b->grib_yy_bs_column = 0;
    }

        b->grib_yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void grib_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->grib_yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->grib_yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->grib_yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->grib_yy_buf_pos = &b->grib_yy_ch_buf[0];

	b->grib_yy_at_bol = 1;
	b->grib_yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		grib_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void grib_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	grib_yyensure_buffer_stack();

	/* This block is copied from grib_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(grib_yy_c_buf_p) = (grib_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_pos = (grib_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(grib_yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from grib_yy_switch_to_buffer. */
	grib_yy_load_buffer_state( );
	(grib_yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void grib_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	grib_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((grib_yy_buffer_stack_top) > 0)
		--(grib_yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		grib_yy_load_buffer_state( );
		(grib_yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void grib_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(grib_yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(grib_yy_buffer_stack) = (struct grib_yy_buffer_state**)grib_yyalloc
								(num_to_alloc * sizeof(struct grib_yy_buffer_state*)
								);
		if ( ! (grib_yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in grib_yyensure_buffer_stack()" );
								  
		memset((grib_yy_buffer_stack), 0, num_to_alloc * sizeof(struct grib_yy_buffer_state*));
				
		(grib_yy_buffer_stack_max) = num_to_alloc;
		(grib_yy_buffer_stack_top) = 0;
		return;
	}

	if ((grib_yy_buffer_stack_top) >= ((grib_yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (grib_yy_buffer_stack_max) + grow_size;
		(grib_yy_buffer_stack) = (struct grib_yy_buffer_state**)grib_yyrealloc
								((grib_yy_buffer_stack),
								num_to_alloc * sizeof(struct grib_yy_buffer_state*)
								);
		if ( ! (grib_yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in grib_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((grib_yy_buffer_stack) + (grib_yy_buffer_stack_max), 0, grow_size * sizeof(struct grib_yy_buffer_state*));
		(grib_yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE grib_yy_scan_buffer  (char * base, grib_yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) grib_yyalloc(sizeof( struct grib_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_scan_buffer()" );

	b->grib_yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->grib_yy_buf_pos = b->grib_yy_ch_buf = base;
	b->grib_yy_is_our_buffer = 0;
	b->grib_yy_input_file = 0;
	b->grib_yy_n_chars = b->grib_yy_buf_size;
	b->grib_yy_is_interactive = 0;
	b->grib_yy_at_bol = 1;
	b->grib_yy_fill_buffer = 0;
	b->grib_yy_buffer_status = YY_BUFFER_NEW;

	grib_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to grib_yylex() will
 * scan from a @e copy of @a str.
 * @param grib_yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       grib_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE grib_yy_scan_string (grib_yyconst char * grib_yystr )
{
    
	return grib_yy_scan_bytes(grib_yystr,strlen(grib_yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to grib_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE grib_yy_scan_bytes  (grib_yyconst char * grib_yybytes, int  _grib_yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	grib_yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _grib_yybytes_len + 2;
	buf = (char *) grib_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_scan_bytes()" );

	for ( i = 0; i < _grib_yybytes_len; ++i )
		buf[i] = grib_yybytes[i];

	buf[_grib_yybytes_len] = buf[_grib_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = grib_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in grib_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->grib_yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void grib_yy_fatal_error (grib_yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine grib_yyless() so it works in section 3 code. */

#undef grib_yyless
#define grib_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up grib_yytext. */ \
        int grib_yyless_macro_arg = (n); \
        YY_LESS_LINENO(grib_yyless_macro_arg);\
		grib_yytext[grib_yyleng] = (grib_yy_hold_char); \
		(grib_yy_c_buf_p) = grib_yytext + grib_yyless_macro_arg; \
		(grib_yy_hold_char) = *(grib_yy_c_buf_p); \
		*(grib_yy_c_buf_p) = '\0'; \
		grib_yyleng = grib_yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int grib_yyget_lineno  (void)
{
        
    return grib_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *grib_yyget_in  (void)
{
        return grib_yyin;
}

/** Get the output stream.
 * 
 */
FILE *grib_yyget_out  (void)
{
        return grib_yyout;
}

/** Get the length of the current token.
 * 
 */
int grib_yyget_leng  (void)
{
        return grib_yyleng;
}

/** Get the current token.
 * 
 */

char *grib_yyget_text  (void)
{
        return grib_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void grib_yyset_lineno (int  line_number )
{
    
    grib_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see grib_yy_switch_to_buffer
 */
void grib_yyset_in (FILE *  in_str )
{
        grib_yyin = in_str ;
}

void grib_yyset_out (FILE *  out_str )
{
        grib_yyout = out_str ;
}

int grib_yyget_debug  (void)
{
        return grib_yy_flex_debug;
}

void grib_yyset_debug (int  bdebug )
{
        grib_yy_flex_debug = bdebug ;
}

static int grib_yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from grib_yylex_destroy(), so don't allocate here.
     */

    (grib_yy_buffer_stack) = 0;
    (grib_yy_buffer_stack_top) = 0;
    (grib_yy_buffer_stack_max) = 0;
    (grib_yy_c_buf_p) = (char *) 0;
    (grib_yy_init) = 0;
    (grib_yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    grib_yyin = stdin;
    grib_yyout = stdout;
#else
    grib_yyin = (FILE *) 0;
    grib_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * grib_yylex_init()
     */
    return 0;
}

/* grib_yylex_destroy is for both reentrant and non-reentrant scanners. */
int grib_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		grib_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		grib_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	grib_yyfree((grib_yy_buffer_stack) );
	(grib_yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * grib_yylex() is called, initialization will occur. */
    grib_yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef grib_yytext_ptr
static void grib_yy_flex_strncpy (char* s1, grib_yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int grib_yy_flex_strlen (grib_yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *grib_yyalloc (grib_yy_size_t  size )
{
	return (void *) malloc( size );
}

void *grib_yyrealloc  (void * ptr, grib_yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void grib_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see grib_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "grib_yytables"

#line 226 "gribl.l"




