/* This file is automatically generated by ./make_class.pl, do not edit */
extern grib_iterator_class* grib_iterator_class_gaussian;
extern grib_iterator_class* grib_iterator_class_gaussian_reduced;
extern grib_iterator_class* grib_iterator_class_gen;
extern grib_iterator_class* grib_iterator_class_lambert_azimuthal_equal_area;
extern grib_iterator_class* grib_iterator_class_lambert_conformal;
extern grib_iterator_class* grib_iterator_class_latlon;
extern grib_iterator_class* grib_iterator_class_latlon_reduced;
extern grib_iterator_class* grib_iterator_class_polar_stereographic;
extern grib_iterator_class* grib_iterator_class_regular;
