/* This file is automatically generated by ./make_class.pl, do not edit */
{ "gen", &grib_box_class_gen, },
{ "reduced_gaussian", &grib_box_class_reduced_gaussian, },
{ "regular_gaussian", &grib_box_class_regular_gaussian, },
