
#line 3 "lex.grib_yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define grib_yyconst const
#else
#define grib_yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (grib_yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((grib_yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE grib_yyrestart(grib_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(grib_yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct grib_yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int grib_yyleng;

extern FILE *grib_yyin, *grib_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define grib_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up grib_yytext. */ \
        int grib_yyless_macro_arg = (n); \
        YY_LESS_LINENO(grib_yyless_macro_arg);\
		*grib_yy_cp = (grib_yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(grib_yy_c_buf_p) = grib_yy_cp = grib_yy_bp + grib_yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up grib_yytext again */ \
		} \
	while ( 0 )

#define unput(c) grib_yyunput( c, (grib_yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t grib_yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct grib_yy_buffer_state
	{
	FILE *grib_yy_input_file;

	char *grib_yy_ch_buf;		/* input buffer */
	char *grib_yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	grib_yy_size_t grib_yy_buf_size;

	/* Number of characters read into grib_yy_ch_buf, not including EOB
	 * characters.
	 */
	int grib_yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int grib_yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int grib_yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int grib_yy_at_bol;

    int grib_yy_bs_lineno; /**< The line count. */
    int grib_yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int grib_yy_fill_buffer;

	int grib_yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via grib_yyrestart()), so that the user can continue scanning by
	 * just pointing grib_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t grib_yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t grib_yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * grib_yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (grib_yy_buffer_stack) \
                          ? (grib_yy_buffer_stack)[(grib_yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (grib_yy_buffer_stack)[(grib_yy_buffer_stack_top)]

/* grib_yy_hold_char holds the character lost when grib_yytext is formed. */
static char grib_yy_hold_char;
static int grib_yy_n_chars;		/* number of characters read into grib_yy_ch_buf */
int grib_yyleng;

/* Points to current character in buffer. */
static char *grib_yy_c_buf_p = (char *) 0;
static int grib_yy_init = 0;		/* whether we need to initialize */
static int grib_yy_start = 0;	/* start state number */

/* Flag which is used to allow grib_yywrap()'s to do buffer switches
 * instead of setting up a fresh grib_yyin.  A bit of a hack ...
 */
static int grib_yy_did_buffer_switch_on_eof;

void grib_yyrestart (FILE *input_file  );
void grib_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE grib_yy_create_buffer (FILE *file,int size  );
void grib_yy_delete_buffer (YY_BUFFER_STATE b  );
void grib_yy_flush_buffer (YY_BUFFER_STATE b  );
void grib_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void grib_yypop_buffer_state (void );

static void grib_yyensure_buffer_stack (void );
static void grib_yy_load_buffer_state (void );
static void grib_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER grib_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE grib_yy_scan_buffer (char *base,grib_yy_size_t size  );
YY_BUFFER_STATE grib_yy_scan_string (grib_yyconst char *grib_yy_str  );
YY_BUFFER_STATE grib_yy_scan_bytes (grib_yyconst char *bytes,int len  );

void *grib_yyalloc (grib_yy_size_t  );
void *grib_yyrealloc (void *,grib_yy_size_t  );
void grib_yyfree (void *  );

#define grib_yy_new_buffer grib_yy_create_buffer

#define grib_yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        grib_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->grib_yy_is_interactive = is_interactive; \
	}

#define grib_yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        grib_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->grib_yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->grib_yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *grib_yyin = (FILE *) 0, *grib_yyout = (FILE *) 0;

typedef int grib_yy_state_type;

extern int grib_yylineno;

int grib_yylineno = 1;

extern char *grib_yytext;
#define grib_yytext_ptr grib_yytext

static grib_yy_state_type grib_yy_get_previous_state (void );
static grib_yy_state_type grib_yy_try_NUL_trans (grib_yy_state_type current_state  );
static int grib_yy_get_next_buffer (void );
static void grib_yy_fatal_error (grib_yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up grib_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(grib_yytext_ptr) = grib_yy_bp; \
	grib_yyleng = (size_t) (grib_yy_cp - grib_yy_bp); \
	(grib_yy_hold_char) = *grib_yy_cp; \
	*grib_yy_cp = '\0'; \
	(grib_yy_c_buf_p) = grib_yy_cp;

#define YY_NUM_RULES 103
#define YY_END_OF_BUFFER 104
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct grib_yy_trans_info
	{
	flex_int32_t grib_yy_verify;
	flex_int32_t grib_yy_nxt;
	};
static grib_yyconst flex_int16_t grib_yy_accept[517] =
    {   0,
      100,  100,  104,  102,  100,  101,   12,   94,   99,  102,
      102,   97,    5,  102,    3,   96,   96,   96,   95,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,  102,
       18,  100,    6,   14,    0,    0,   97,    4,    7,    1,
        2,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   20,   96,   10,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   15,   96,   96,   96,   96,   96,   96,   96,   96,

       96,   96,   96,   96,   96,   96,   96,   16,   98,   96,
       21,   96,   13,   96,   96,   96,    8,   58,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       32,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   11,   96,   96,   45,   96,   96,   96,   96,
       96,   81,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,    0,   96,   96,   96,   96,   96,
       25,   96,   84,   96,   96,   96,   96,   96,   96,   96,
       73,   96,   22,   96,   96,   96,   96,   96,   96,   96,

       96,   96,   96,   96,   59,   96,   96,   27,   96,   96,
       96,   96,   41,   96,   96,   96,   96,   96,   17,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   92,   96,
       96,   96,   96,   96,   96,   96,   83,   96,   96,    0,
       98,   96,   48,   96,   24,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   39,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   26,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       43,   96,   91,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   28,   89,   96,   90,   69,

       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       66,   96,   96,   96,   96,   37,   75,   96,   96,   96,
       96,   96,   68,   96,   40,   96,   96,   62,   96,   96,
       96,    9,   96,   96,   96,   96,   96,   67,   96,   96,
       35,   96,   85,   96,   96,   96,   96,   96,   77,   96,
       96,   96,   87,   96,   96,   80,   86,   96,   96,   60,
       96,   96,   96,   96,   96,   93,   96,   96,   96,   96,
       47,   57,   71,   74,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   31,   49,   96,   96,   96,   96,
       96,   51,   96,   96,   96,   96,   96,   96,   33,   96,

       56,   96,   96,   96,   79,   96,   96,   50,   96,   96,
       96,   96,   29,   96,   23,   96,   36,   96,   96,   96,
       96,   96,   96,   96,   96,   34,   96,   54,   19,   42,
       96,   70,   96,   96,   96,   96,   52,   96,   96,   96,
       78,   96,   96,   96,   96,   96,   96,   96,   96,   82,
       96,   96,   96,   96,   96,   55,   96,   96,   96,   96,
       61,   96,   96,   53,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   44,   96,   96,   76,   96,   88,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   46,

       30,   96,   72,   96,   96,   96,   38,   96,   64,   96,
       96,   65,   96,   96,   63,    0
    } ;

static grib_yyconst flex_int32_t grib_yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    8,    1,
        1,    1,    9,    1,    9,   10,    1,   11,   12,   11,
       11,   13,   11,   11,   11,   11,   11,    1,    1,   14,
       15,   16,    1,    1,   17,   17,   17,   17,   18,   17,
       19,   17,   20,   17,   17,   17,   21,   22,   17,   17,
       17,   17,   23,   17,   17,   17,   17,   17,   17,   17,
        1,    1,    1,    1,   24,   25,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   17,   35,   36,   37,   38,
       39,   40,   17,   41,   42,   43,   44,   45,   46,   47,
       48,   17,    1,   49,    1,   50,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static grib_yyconst flex_int32_t grib_yy_meta[51] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    2,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1
    } ;

static grib_yyconst flex_int16_t grib_yy_base[519] =
    {   0,
        0,    0,  329, 2090,  326, 2090,  311, 2090, 2090,  315,
       40,   44,   43,  306,  286,   49,   52,   55, 2090,   58,
       63,   66,   69,   74,   48,  106,  111,  119,   89,  126,
      114,  137,  157,  148,  149,  160,  166,  197,  200,  251,
     2090,  293, 2090, 2090,  122,  130,  204, 2090, 2090, 2090,
     2090,    0,  207,  211,  214,  217,  225,  231,  235,  244,
      247,  253,  232,  244,  277,  280,  286,  291,  294,  298,
      301,  304,  261,  307,  320,  326,  331,  334,  340,  343,
      346,  353,  358,  361,  366,  375,  369,  378,  383,  391,
      405,  411,  414,  417,  420,  424,  427,  437,  443,  448,

      455,  458,  461,  367,  451,  461,  471, 2090,  491,  495,
      500,  503,  511,  514,  519,  522,  525,  528,  534,  537,
      543,  546,  554,  557,  566,  569,  575,  578,  585,  592,
      595,  598,  604,  410,  608,  612,  618,  621,  631,  634,
      641,  644,  647,  650,  653,  659,  665,  669,  675,  678,
      685,  691,  694,  697,  702,  705,  712,  716,  723,  719,
      726,  729,  738,  744,  748,  751,  755,  759,  766,  774,
      762,  777,  780,  788,  793,  800,  796,  806,  811,  814,
      817,  821,  824,  828,  838,  845,  841,  848,  851,  854,
      857,  865,  868,  874,  880,  257,  249,  248,  885,  889,

      892,  898,  901,  905,  913,  921,  924,  927,  930,  935,
      939,  947,  950,  953,  957,  963,  970,  977,  980,  986,
      992,  995, 1001, 1004, 1007, 1011, 1021, 1024, 1028, 1035,
     1038, 1044, 1049, 1052, 1056, 1063, 1059, 1066, 1070, 1074,
     1081, 1086, 1090, 1093, 1098, 1101, 1104, 1107, 1112, 1115,
     1119, 1124, 1128, 1135, 1138, 1141, 1145, 1155,  240,  233,
      241, 1158, 1161, 1169, 1174, 1177, 1180,  237, 1183, 1189,
     1200, 1204, 1207, 1213, 1216, 1219, 1225, 1228, 1235, 1238,
     1243, 1247, 1255, 1258, 1263, 1271, 1274, 1277, 1283, 1287,
     1290, 1296, 1306, 1311, 1314, 1320, 1327, 1330, 1333, 1342,

     1345, 1348, 1351, 1354, 1361, 1365, 1368, 1371, 1376, 1381,
     1393, 1396,  231,  219,  210, 1399, 1404, 1409, 1412, 1415,
     1418,  205, 1421, 1425, 1429, 1435, 1441, 1447, 1451, 1454,
     1457, 1463, 1466, 1469, 1472, 1476, 1479, 1485, 1488, 1492,
     1495, 1498, 1507, 1516, 1519, 1522, 1525, 1528, 1531, 1534,
     1539, 1542, 1549, 1557, 1565, 1568, 1571, 1574, 1577, 1580,
      226,  223,  206, 1583, 1592, 1595, 1598,  199, 1601, 1608,
     1611, 1616, 1619, 1622, 1625, 1631, 1634, 1640, 1645, 1651,
     1654, 1660, 1671, 1674, 1677, 1680, 1684, 1687, 1693, 1696,
     1703, 1706, 1714, 1717, 1720,  205,  199,  182, 1723, 1726,

     1731,  159, 1734, 1737, 1742, 1745, 1748, 1759, 1762, 1765,
     1768, 1773, 1776, 1781, 1784, 1795, 1800, 1803, 1806, 1814,
     1818, 1821,  153,  167,  155, 1827,  161, 1835, 1838, 1841,
     1851, 1854, 1857, 1860, 1863, 1866, 1869, 1875, 1878, 1881,
     1886, 1889, 1897,  142,  160,  167,  136, 1902, 1909, 1912,
     1917, 1920, 1923, 1928, 1937, 1932, 1940,  143,  136,  142,
        0, 1943, 1949, 1953, 1958, 1961, 1964, 1969, 1972,  140,
      128,  118, 1975, 1979, 1982, 1985, 1989, 1998, 2007,  123,
      109,  100, 2010, 2013, 2016, 2019, 2028, 2024, 2031,   89,
       94,   82, 2034, 2041, 2045, 2048,   86,   66,   75, 2051,

     2056, 2059, 2062,   76,   71,   58, 2067,   64,    0,   60,
       55,    0,   61,   53,    0, 2090,   81,   71
    } ;

static grib_yyconst flex_int16_t grib_yy_def[519] =
    {   0,
      516,    1,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  517,  517,  517,  516,  517,
      517,  517,  517,   20,   20,  517,  517,   20,   20,  517,
       30,   30,  517,   30,   30,   30,   30,  517,  517,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  518,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,   20,   20,  517,  517,  517,  517,  517,  517,
      517,  517,  518,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,

      517,  517,  517,   30,   30,   30,   30,  516,  516,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  518,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  516,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  518,  518,  518,  517,  517,

      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  516,
      516,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  518,  518,
      518,  517,  517,  517,  517,  517,  517,  518,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,

      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  518,  518,  518,  517,  517,  517,  517,  517,
      517,  518,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      518,  518,  518,  517,  517,  517,  517,  518,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  518,  518,  518,  517,  517,

      517,  518,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  518,  518,  518,  517,  518,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  518,  518,  518,  518,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  518,  518,  518,
      518,  517,  517,  517,  517,  517,  517,  517,  517,  518,
      518,  518,  517,  517,  517,  517,  517,  517,  517,  518,
      518,  518,  517,  517,  517,  517,  517,  517,  517,  518,
      518,  518,  517,  517,  517,  517,  518,  518,  518,  517,

      517,  517,  517,  518,  518,  518,  517,  518,  518,  518,
      518,  518,  518,  518,  518,    0,  516,  516
    } ;

static grib_yyconst flex_int16_t grib_yy_nxt[2141] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    8,   11,    4,
       12,   12,   12,   13,   14,   15,   16,   16,   16,   16,
       17,   16,   16,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   16,   39,   16,   16,   40,   41,
       45,   45,   45,   46,   47,   47,   47,   48,   49,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   54,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   53,   72,  515,   53,  514,   53,   55,   53,
      513,   63,  512,   56,  511,   57,   60,   58,   65,   59,

      510,   61,   68,  509,   64,  508,  506,   66,  505,   69,
       62,   70,   67,   53,  504,   53,   52,   73,   52,  499,
       71,   52,   52,   52,   53,  498,   53,  497,   53,  492,
       82,   46,   45,   45,   45,   74,   52,   52,   52,   53,
      109,  109,  109,   87,   75,   76,  491,   53,   77,   78,
      490,   83,   88,  482,   53,   84,   79,  481,   53,   85,
       80,   81,   53,  480,   86,  472,   89,   52,   52,   52,
       53,  471,  470,   94,   53,   90,  461,   53,   97,  460,
       91,   53,   53,  459,  458,   53,   95,   53,   96,   98,
      447,   53,  446,   99,  100,  103,  445,   92,   53,   53,

      444,   93,  101,  427,   53,  102,  104,   52,   52,   52,
       52,   52,   52,   46,   47,   47,   47,   52,   52,   52,
      425,   52,   52,   52,   52,   52,   52,   52,   52,   52,
      424,  423,  106,  110,  105,   52,   52,   52,  402,  398,
      107,   52,   52,   52,  111,   52,   52,   52,  397,  396,
      112,  368,  363,  113,   52,   52,   52,   52,   52,   52,
      362,  361,  115,   52,   52,   52,  322,   53,  315,  120,
      114,   53,  122,  121,  314,  313,  116,  261,  260,   53,
      123,  124,  259,  125,  134,   53,  117,   52,   52,   52,
       52,   52,   52,  118,   42,  119,   52,   52,   52,  108,

       51,   52,   52,   52,   52,   52,   52,  126,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       50,   44,  128,  127,  129,   43,  131,   42,  516,  133,
       52,   52,   52,  516,  516,  130,   52,   52,   52,  516,
      132,   52,   52,   52,   52,   52,   52,  516,  136,  135,
       52,   52,   52,   52,   52,   52,   52,   52,   52,  516,
      138,  516,  137,   52,   52,   52,  516,  139,   52,   52,
       52,   52,   52,   52,  516,  140,   52,   52,   52,   52,
       52,   52,  141,  516,  142,   52,   52,   52,   52,   52,
       52,  516,  168,   52,   52,   52,   53,  516,  143,  516,

      169,   52,   52,   52,  516,   53,  150,  144,  151,  516,
      148,  149,  145,  146,  152,   52,   52,   52,  516,  516,
      147,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,  153,   52,   52,   52,   52,   52,   52,
      154,  516,  196,  155,  516,  156,  197,   52,   52,   52,
      516,  198,  159,   52,   52,   52,  516,  158,   52,   52,
       52,  157,  516,  160,  161,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  163,  516,  170,  516,  516,  162,
       53,  164,  516,  516,   53,  516,   53,  516,  516,   53,
      172,  166,  171,  516,  173,  165,   53,  167,  516,   53,

       53,  109,  109,  109,  174,   52,   52,   52,  175,   53,
       52,   52,   52,   52,   52,   52,  516,  176,  516,  516,
      175,   52,   52,   52,   52,   52,   52,  516,  177,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,  516,  516,  178,   52,   52,   52,   52,   52,   52,
      516,  180,  179,   52,   52,   52,   52,   52,   52,  516,
      182,  516,  516,  181,   52,   52,   52,   52,   52,   52,
      516,  516,  183,  516,  516,  184,   52,   52,   52,   52,
       52,   52,  516,  516,  186,   52,   52,   52,   52,   52,
       52,  516,  516,  185,  189,   52,   52,   52,  187,  516,

      516,  190,   52,   52,   52,   52,   52,   52,   52,   52,
       52,  516,  516,  188,   52,   52,   52,  191,   52,   52,
       52,  193,   52,   52,   52,  516,  516,  192,   52,   52,
       52,   52,   52,   52,  516,  195,  194,  199,  516,  516,
      200,   52,   52,   52,   52,   52,   52,  516,  201,  516,
      202,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  203,  516,  205,   52,
       52,   52,  516,  206,  204,   52,   52,   52,  207,   52,
       52,   52,  516,  516,  209,   52,   52,   52,   52,   52,
       52,  516,  208,  210,  211,   52,   52,   52,  516,  516,

      213,   52,   52,   52,   52,   52,   52,   52,   52,   52,
      212,  214,   52,   52,   52,   52,   52,   52,  216,  516,
      218,  217,   52,   52,   52,  215,   52,   52,   52,   52,
       52,   52,  219,   52,   52,   52,   52,   52,   52,   52,
       52,   52,  220,  516,  516,  222,  516,  221,   52,   52,
       52,  224,  227,  223,   52,   52,   52,  225,   52,   52,
       52,   52,   52,   52,  516,   52,   52,   52,  226,   52,
       52,   52,   52,   52,   52,  228,   52,   52,   52,  516,
      516,  230,  516,  229,   52,   52,   52,   52,   52,   52,
       52,   52,   52,  231,  232,  236,  233,  234,   52,   52,

       52,  240,  516,  241,  241,  241,   52,   52,   52,  235,
       52,   52,   52,  516,  237,  238,   52,   52,   52,  242,
      516,   52,   52,   52,   52,   52,   52,   52,   52,   52,
      239,   52,   52,   52,   52,   52,   52,  243,   52,   52,
       52,  516,  516,  244,  245,  516,  516,  247,   52,   52,
       52,   52,   52,   52,  246,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
      248,  252,  516,  249,  250,   52,   52,   52,   52,   52,
       52,  516,  516,  251,   52,   52,   52,  516,  516,  254,
       52,   52,   52,  516,  253,   52,   52,   52,  255,   52,

       52,   52,   52,   52,   52,  516,  257,  516,   52,   52,
       52,   52,   52,   52,  256,   52,   52,   52,  263,  516,
      516,  258,  262,   52,  268,   52,  516,  264,  265,  516,
      267,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,  516,  266,   52,   52,   52,  516,   52,
       52,   52,  516,  271,  516,  516,  269,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  270,   52,   52,   52,
      516,  516,  274,   52,   52,   52,  516,  516,  272,  273,
       52,   52,   52,  275,  516,  516,  276,   52,   52,   52,
       52,   52,   52,  516,  516,  278,   52,   52,   52,  516,

      516,  277,   52,   52,   52,   52,   52,   52,  516,  516,
      279,   52,   52,   52,   52,   52,   52,   52,   52,   52,
      516,   52,   52,   52,  516,  516,  280,  284,  516,  516,
      281,   52,   52,   52,   52,   52,   52,  282,   52,   52,
       52,  516,  516,  283,  286,   52,   52,   52,   52,   52,
       52,  285,  516,  288,   52,   52,   52,  516,  287,   52,
       52,   52,   52,   52,   52,  290,   52,   52,   52,   52,
       52,   52,  289,   52,   52,   52,   52,   52,   52,  291,
       52,   52,   52,  293,  241,  241,  241,  516,  516,  294,
      292,  241,  241,  241,  295,  296,   52,   52,   52,  297,

       52,   52,   52,   52,   52,   52,  516,  298,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
      516,  299,   52,   52,   52,   52,   52,   52,  516,   52,
       52,   52,  302,  301,   52,   52,   52,  516,   52,   52,
       52,  303,  516,  300,  305,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  304,   52,   52,   52,  516,  306,
      516,  516,  307,  308,  309,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  516,  516,  310,  516,  312,   52,
       52,   52,  516,  311,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  516,  516,  317,   52,

       52,   52,  316,  516,  516,  320,  516,  318,  516,  319,
       52,   52,   52,  516,   52,   52,   52,   52,   52,   52,
      516,  323,  321,   52,   52,   52,   52,   52,   52,   52,
       52,   52,  516,  516,  326,   52,   52,   52,   52,   52,
       52,  516,  324,  325,  327,   52,   52,   52,   52,   52,
       52,  516,  516,   52,   52,   52,  516,   52,   52,   52,
      329,  331,  516,  328,  330,   52,   52,   52,   52,   52,
       52,  333,  334,   52,   52,   52,  516,  332,  516,  335,
      336,   52,   52,   52,   52,   52,   52,   52,   52,   52,
      516,  516,  338,   52,   52,   52,  337,   52,   52,   52,

       52,   52,   52,  516,  516,  341,   52,   52,   52,  339,
      516,  516,  340,  516,  342,  344,   52,   52,   52,  343,
      516,   52,   52,   52,   52,   52,   52,  516,  516,  345,
       52,   52,   52,  516,  516,  346,  347,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  516,  516,  349,  516,
      516,  348,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,  516,  350,  516,
      516,   52,   52,   52,  351,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  516,  516,   52,   52,   52,  516,
      355,   52,   52,   52,  516,  516,  353,  352,  354,  358,

      516,  516,  356,   52,   52,   52,   52,   52,   52,   52,
       52,   52,  516,  357,   52,   52,   52,  516,  359,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  364,   52,   52,   52,  360,   52,
       52,   52,  516,  516,  366,   52,   52,   52,  516,  516,
      365,   52,   52,   52,  516,  516,  367,   52,   52,   52,
      370,   52,   52,   52,   52,   52,   52,   52,   52,   52,
      371,  516,  369,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,  516,   52,   52,   52,   52,
       52,   52,  374,  372,  375,   52,   52,   52,   52,   52,

       52,  373,   52,   52,   52,   52,   52,   52,   52,   52,
       52,  516,  516,  376,  378,  377,  379,   52,   52,   52,
      516,  382,  381,  516,  516,  380,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,  516,  384,   52,
       52,   52,   52,   52,   52,  516,  516,  387,  383,   52,
       52,   52,  385,  516,  516,  390,  386,   52,   52,   52,
      388,  516,  391,  516,  389,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  516,  516,  393,  392,

      395,  516,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  516,  516,  394,  400,   52,   52,
       52,   52,   52,   52,  516,  399,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  401,  516,
      403,   52,   52,   52,   52,   52,   52,  516,  516,  404,
       52,   52,   52,  516,  405,   52,   52,   52,  516,  516,
      406,   52,   52,   52,   52,   52,   52,  516,  516,  407,
       52,   52,   52,  516,  410,  516,  516,  408,  516,  411,
      409,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,  516,   52,   52,   52,   52,   52,   52,

      413,  516,  412,   52,   52,   52,   52,   52,   52,  516,
      516,  414,  415,   52,   52,   52,   52,   52,   52,  516,
      416,  516,  417,  418,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,  516,
      419,   52,   52,   52,   52,   52,   52,   52,   52,   52,
      516,  420,   52,   52,   52,   52,   52,   52,   52,   52,
       52,  422,  516,  428,  421,  516,  429,  516,  426,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,  516,  430,   52,   52,   52,   52,   52,   52,  516,
      431,   52,   52,   52,   52,   52,   52,  516,  516,  436,

      516,  434,  516,  516,  433,   52,   52,   52,  516,  432,
       52,   52,   52,   52,   52,   52,   52,   52,   52,  516,
      435,  516,  516,  437,   52,   52,   52,  516,   52,   52,
       52,   52,   52,   52,  516,  516,  438,   52,   52,   52,
      516,  439,  516,  516,  440,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  516,  516,  441,  442,  516,  516,
      443,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,  449,  516,  448,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  516,  450,   52,   52,   52,   52,

       52,   52,  451,  452,  516,  516,  454,   52,   52,   52,
      516,  455,   52,   52,   52,  516,  453,  516,  456,   52,
       52,   52,   52,   52,   52,  516,  457,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  516,  463,   52,   52,
       52,  462,   52,   52,   52,  516,  464,   52,   52,   52,
       52,   52,   52,   52,   52,   52,  466,  467,  465,   52,
       52,   52,  468,   52,   52,   52,  516,  469,   52,   52,
       52,   52,   52,   52,   52,   52,   52,  474,  473,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  475,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  476,   52,

       52,   52,  478,  516,  483,  479,  477,  485,   52,   52,
       52,  516,  484,  516,  487,  516,  486,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,  516,  488,   52,   52,   52,  489,   52,   52,
       52,   52,   52,   52,   52,   52,   52,  516,  516,  494,
      493,   52,   52,   52,  495,   52,   52,   52,   52,   52,
       52,   52,   52,   52,  496,  500,   52,   52,   52,   52,
       52,   52,   52,   52,   52,  503,  501,   52,   52,   52,
      502,  516,  516,  516,  516,  516,  516,  516,  507,    3,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,

      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516
    } ;

static grib_yyconst flex_int16_t grib_yy_chk[2141] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       11,   11,   11,   12,   12,   12,   12,   13,   13,   16,
       16,   16,   17,   17,   17,   18,   18,   18,   20,   20,
       20,   17,  518,   21,   21,   21,   22,   22,   22,   23,
       23,   23,  517,   25,  514,   25,  513,   25,   18,   25,
      511,   22,  510,   20,  508,   20,   21,   20,   23,   20,

      506,   21,   24,  505,   22,  504,  499,   23,  498,   24,
       21,   24,   23,   24,  497,   24,   26,   26,   26,  492,
       24,   27,   27,   27,   29,  491,   29,  490,   29,  482,
       29,   45,   45,   45,   45,   26,   30,   30,   30,   31,
       46,   46,   46,   31,   27,   28,  481,   31,   28,   28,
      480,   30,   31,  472,   28,   30,   28,  471,   28,   30,
       28,   28,   32,  470,   30,  460,   32,   33,   33,   33,
       32,  459,  458,   34,   35,   32,  447,   34,   35,  446,
       32,   34,   35,  445,  444,   36,   34,   35,   34,   36,
      427,   37,  425,   36,   36,   37,  424,   33,   36,   37,

      423,   33,   36,  402,   37,   36,   37,   38,   38,   38,
       39,   39,   39,   47,   47,   47,   47,   53,   53,   53,
      398,   54,   54,   54,   55,   55,   55,   56,   56,   56,
      397,  396,   39,   54,   38,   57,   57,   57,  368,  363,
       39,   58,   58,   58,   55,   59,   59,   59,  362,  361,
       56,  322,  315,   57,   60,   60,   60,   61,   61,   61,
      314,  313,   59,   62,   62,   62,  268,   63,  261,   63,
       58,   63,   64,   63,  260,  259,   59,  198,  197,   64,
       64,   64,  196,   64,   73,   64,   60,   65,   65,   65,
       66,   66,   66,   61,   42,   62,   67,   67,   67,   40,

       15,   68,   68,   68,   69,   69,   69,   65,   70,   70,
       70,   71,   71,   71,   72,   72,   72,   74,   74,   74,
       14,   10,   67,   66,   68,    7,   70,    5,    3,   72,
       75,   75,   75,    0,    0,   69,   76,   76,   76,    0,
       71,   77,   77,   77,   78,   78,   78,    0,   75,   74,
       79,   79,   79,   80,   80,   80,   81,   81,   81,    0,
       77,    0,   76,   82,   82,   82,    0,   79,   83,   83,
       83,   84,   84,   84,    0,   81,   85,   85,   85,   87,
       87,   87,   82,    0,   83,   86,   86,   86,   88,   88,
       88,    0,  104,   89,   89,   89,  104,    0,   84,    0,

      104,   90,   90,   90,    0,  104,   88,   85,   89,    0,
       87,   87,   86,   86,   90,   91,   91,   91,    0,    0,
       86,   92,   92,   92,   93,   93,   93,   94,   94,   94,
       95,   95,   95,   90,   96,   96,   96,   97,   97,   97,
       91,    0,  134,   93,    0,   94,  134,   98,   98,   98,
        0,  134,   97,   99,   99,   99,    0,   96,  100,  100,
      100,   95,    0,   97,   98,  101,  101,  101,  102,  102,
      102,  103,  103,  103,   99,    0,  105,    0,    0,   98,
      105,  100,    0,    0,  105,    0,  106,    0,    0,  105,
      106,  102,  105,    0,  106,  101,  107,  103,    0,  106,

      107,  109,  109,  109,  107,  110,  110,  110,  109,  107,
      111,  111,  111,  112,  112,  112,    0,  110,    0,    0,
      109,  113,  113,  113,  114,  114,  114,    0,  112,  115,
      115,  115,  116,  116,  116,  117,  117,  117,  118,  118,
      118,    0,    0,  114,  119,  119,  119,  120,  120,  120,
        0,  116,  115,  121,  121,  121,  122,  122,  122,    0,
      120,    0,    0,  119,  123,  123,  123,  124,  124,  124,
        0,    0,  121,    0,    0,  122,  125,  125,  125,  126,
      126,  126,    0,    0,  124,  127,  127,  127,  128,  128,
      128,    0,    0,  123,  126,  129,  129,  129,  124,    0,

        0,  127,  130,  130,  130,  131,  131,  131,  132,  132,
      132,    0,    0,  125,  133,  133,  133,  128,  135,  135,
      135,  130,  136,  136,  136,    0,    0,  129,  137,  137,
      137,  138,  138,  138,    0,  133,  132,  135,    0,    0,
      136,  139,  139,  139,  140,  140,  140,    0,  137,    0,
      138,  141,  141,  141,  142,  142,  142,  143,  143,  143,
      144,  144,  144,  145,  145,  145,  139,    0,  141,  146,
      146,  146,    0,  142,  140,  147,  147,  147,  143,  148,
      148,  148,    0,    0,  145,  149,  149,  149,  150,  150,
      150,    0,  144,  146,  147,  151,  151,  151,    0,    0,

      149,  152,  152,  152,  153,  153,  153,  154,  154,  154,
      148,  150,  155,  155,  155,  156,  156,  156,  152,    0,
      153,  152,  157,  157,  157,  151,  158,  158,  158,  160,
      160,  160,  154,  159,  159,  159,  161,  161,  161,  162,
      162,  162,  155,    0,    0,  157,    0,  156,  163,  163,
      163,  159,  162,  158,  164,  164,  164,  160,  165,  165,
      165,  166,  166,  166,    0,  167,  167,  167,  161,  168,
      168,  168,  171,  171,  171,  163,  169,  169,  169,    0,
        0,  165,    0,  164,  170,  170,  170,  172,  172,  172,
      173,  173,  173,  166,  167,  171,  168,  169,  174,  174,

      174,  175,    0,  175,  175,  175,  177,  177,  177,  170,
      176,  176,  176,    0,  172,  173,  178,  178,  178,  176,
        0,  179,  179,  179,  180,  180,  180,  181,  181,  181,
      174,  182,  182,  182,  183,  183,  183,  177,  184,  184,
      184,    0,    0,  178,  179,    0,    0,  182,  185,  185,
      185,  187,  187,  187,  180,  186,  186,  186,  188,  188,
      188,  189,  189,  189,  190,  190,  190,  191,  191,  191,
      184,  188,    0,  185,  186,  192,  192,  192,  193,  193,
      193,    0,    0,  187,  194,  194,  194,    0,    0,  190,
      195,  195,  195,    0,  189,  199,  199,  199,  192,  200,

      200,  200,  201,  201,  201,    0,  195,    0,  202,  202,
      202,  203,  203,  203,  194,  204,  204,  204,  200,    0,
        0,  195,  199,  205,  205,  205,    0,  201,  202,    0,
      204,  206,  206,  206,  207,  207,  207,  208,  208,  208,
      209,  209,  209,    0,  203,  210,  210,  210,    0,  211,
      211,  211,    0,  209,    0,    0,  206,  212,  212,  212,
      213,  213,  213,  214,  214,  214,  207,  215,  215,  215,
        0,    0,  212,  216,  216,  216,    0,    0,  210,  211,
      217,  217,  217,  214,    0,    0,  215,  218,  218,  218,
      219,  219,  219,    0,    0,  217,  220,  220,  220,    0,

        0,  216,  221,  221,  221,  222,  222,  222,    0,    0,
      218,  223,  223,  223,  224,  224,  224,  225,  225,  225,
        0,  226,  226,  226,    0,    0,  220,  224,    0,    0,
      221,  227,  227,  227,  228,  228,  228,  222,  229,  229,
      229,    0,    0,  223,  226,  230,  230,  230,  231,  231,
      231,  225,    0,  228,  232,  232,  232,    0,  227,  233,
      233,  233,  234,  234,  234,  231,  235,  235,  235,  237,
      237,  237,  230,  236,  236,  236,  238,  238,  238,  232,
      239,  239,  239,  234,  240,  240,  240,    0,    0,  235,
      233,  241,  241,  241,  236,  238,  242,  242,  242,  239,

      243,  243,  243,  244,  244,  244,    0,  242,  245,  245,
      245,  246,  246,  246,  247,  247,  247,  248,  248,  248,
        0,  244,  249,  249,  249,  250,  250,  250,    0,  251,
      251,  251,  248,  247,  252,  252,  252,    0,  253,  253,
      253,  249,    0,  246,  251,  254,  254,  254,  255,  255,
      255,  256,  256,  256,  250,  257,  257,  257,    0,  251,
        0,    0,  252,  253,  254,  258,  258,  258,  262,  262,
      262,  263,  263,  263,    0,    0,  255,    0,  257,  264,
      264,  264,    0,  256,  265,  265,  265,  266,  266,  266,
      267,  267,  267,  269,  269,  269,    0,    0,  263,  270,

      270,  270,  262,    0,    0,  266,    0,  264,    0,  265,
      271,  271,  271,    0,  272,  272,  272,  273,  273,  273,
        0,  270,  267,  274,  274,  274,  275,  275,  275,  276,
      276,  276,    0,    0,  273,  277,  277,  277,  278,  278,
      278,    0,  271,  272,  274,  279,  279,  279,  280,  280,
      280,    0,    0,  281,  281,  281,    0,  282,  282,  282,
      276,  278,    0,  275,  277,  283,  283,  283,  284,  284,
      284,  280,  281,  285,  285,  285,    0,  279,    0,  281,
      282,  286,  286,  286,  287,  287,  287,  288,  288,  288,
        0,    0,  285,  289,  289,  289,  284,  290,  290,  290,

      291,  291,  291,    0,    0,  288,  292,  292,  292,  286,
        0,    0,  287,    0,  289,  291,  293,  293,  293,  290,
        0,  294,  294,  294,  295,  295,  295,    0,    0,  292,
      296,  296,  296,    0,    0,  293,  294,  297,  297,  297,
      298,  298,  298,  299,  299,  299,    0,    0,  298,    0,
        0,  295,  300,  300,  300,  301,  301,  301,  302,  302,
      302,  303,  303,  303,  304,  304,  304,    0,  301,    0,
        0,  305,  305,  305,  302,  306,  306,  306,  307,  307,
      307,  308,  308,  308,    0,    0,  309,  309,  309,    0,
      306,  310,  310,  310,    0,    0,  304,  303,  305,  309,

        0,    0,  307,  311,  311,  311,  312,  312,  312,  316,
      316,  316,    0,  308,  317,  317,  317,    0,  310,  318,
      318,  318,  319,  319,  319,  320,  320,  320,  321,  321,
      321,  323,  323,  323,  318,  324,  324,  324,  312,  325,
      325,  325,    0,    0,  320,  326,  326,  326,    0,    0,
      319,  327,  327,  327,    0,    0,  321,  328,  328,  328,
      326,  329,  329,  329,  330,  330,  330,  331,  331,  331,
      327,    0,  324,  332,  332,  332,  333,  333,  333,  334,
      334,  334,  335,  335,  335,    0,  336,  336,  336,  337,
      337,  337,  331,  329,  333,  338,  338,  338,  339,  339,

      339,  330,  340,  340,  340,  341,  341,  341,  342,  342,
      342,    0,    0,  334,  336,  335,  337,  343,  343,  343,
        0,  342,  340,    0,    0,  339,  344,  344,  344,  345,
      345,  345,  346,  346,  346,  347,  347,  347,  348,  348,
      348,  349,  349,  349,  350,  350,  350,    0,  345,  351,
      351,  351,  352,  352,  352,    0,    0,  348,  344,  353,
      353,  353,  346,    0,    0,  352,  347,  354,  354,  354,
      350,    0,  353,    0,  351,  355,  355,  355,  356,  356,
      356,  357,  357,  357,  358,  358,  358,  359,  359,  359,
      360,  360,  360,  364,  364,  364,    0,    0,  355,  354,

      359,    0,  365,  365,  365,  366,  366,  366,  367,  367,
      367,  369,  369,  369,    0,    0,  358,  365,  370,  370,
      370,  371,  371,  371,    0,  364,  372,  372,  372,  373,
      373,  373,  374,  374,  374,  375,  375,  375,  367,    0,
      369,  376,  376,  376,  377,  377,  377,    0,    0,  370,
      378,  378,  378,    0,  375,  379,  379,  379,    0,    0,
      376,  380,  380,  380,  381,  381,  381,    0,    0,  377,
      382,  382,  382,    0,  380,    0,    0,  378,    0,  381,
      379,  383,  383,  383,  384,  384,  384,  385,  385,  385,
      386,  386,  386,    0,  387,  387,  387,  388,  388,  388,

      383,    0,  382,  389,  389,  389,  390,  390,  390,    0,
        0,  384,  387,  391,  391,  391,  392,  392,  392,    0,
      388,    0,  389,  390,  393,  393,  393,  394,  394,  394,
      395,  395,  395,  399,  399,  399,  400,  400,  400,    0,
      391,  401,  401,  401,  403,  403,  403,  404,  404,  404,
        0,  393,  405,  405,  405,  406,  406,  406,  407,  407,
      407,  395,    0,  403,  394,    0,  404,    0,  400,  408,
      408,  408,  409,  409,  409,  410,  410,  410,  411,  411,
      411,    0,  406,  412,  412,  412,  413,  413,  413,    0,
      407,  414,  414,  414,  415,  415,  415,    0,    0,  413,

        0,  411,    0,    0,  410,  416,  416,  416,    0,  409,
      417,  417,  417,  418,  418,  418,  419,  419,  419,    0,
      412,    0,    0,  414,  420,  420,  420,    0,  421,  421,
      421,  422,  422,  422,    0,    0,  416,  426,  426,  426,
        0,  418,    0,    0,  419,  428,  428,  428,  429,  429,
      429,  430,  430,  430,    0,    0,  420,  421,    0,    0,
      422,  431,  431,  431,  432,  432,  432,  433,  433,  433,
      434,  434,  434,  435,  435,  435,  436,  436,  436,  437,
      437,  437,  433,    0,  431,  438,  438,  438,  439,  439,
      439,  440,  440,  440,    0,  434,  441,  441,  441,  442,

      442,  442,  435,  436,    0,    0,  439,  443,  443,  443,
        0,  440,  448,  448,  448,    0,  438,    0,  442,  449,
      449,  449,  450,  450,  450,    0,  443,  451,  451,  451,
      452,  452,  452,  453,  453,  453,    0,  449,  454,  454,
      454,  448,  456,  456,  456,    0,  451,  455,  455,  455,
      457,  457,  457,  462,  462,  462,  453,  454,  452,  463,
      463,  463,  455,  464,  464,  464,    0,  457,  465,  465,
      465,  466,  466,  466,  467,  467,  467,  463,  462,  468,
      468,  468,  469,  469,  469,  473,  473,  473,  465,  474,
      474,  474,  475,  475,  475,  476,  476,  476,  466,  477,

      477,  477,  468,    0,  473,  469,  467,  475,  478,  478,
      478,    0,  474,    0,  477,    0,  476,  479,  479,  479,
      483,  483,  483,  484,  484,  484,  485,  485,  485,  486,
      486,  486,    0,  478,  488,  488,  488,  479,  487,  487,
      487,  489,  489,  489,  493,  493,  493,    0,    0,  485,
      484,  494,  494,  494,  487,  495,  495,  495,  496,  496,
      496,  500,  500,  500,  489,  493,  501,  501,  501,  502,
      502,  502,  503,  503,  503,  496,  494,  507,  507,  507,
      495,    0,    0,    0,    0,    0,    0,    0,  502,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,

      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516
    } ;

static grib_yy_state_type grib_yy_last_accepting_state;
static char *grib_yy_last_accepting_cpos;

extern int grib_yy_flex_debug;
int grib_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define grib_yymore() grib_yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *grib_yytext;
#line 1 "gribl.l"
/*
 * Copyright 2005-2014 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * In applying this licence, ECMWF does not waive the privileges and immunities granted to it by
 * virtue of its status as an intergovernmental organisation nor does it submit to any jurisdiction.
 */
#line 13 "gribl.l"
#include "grib_api_internal.h"
#include "grib_yacc.h"
#include <ctype.h>

int grib_yylineno;

/* Keep -Wall quiet */


/*

This is needed for implementing "include", otherwise
flex buffer optimization break the includes.

*/

#define YY_INPUT(buf,result,max_size) \
        { \
        int c = getc(grib_yyin); \
        result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
        }


/*
#ifdef __GNUC__
#ifdef FLEX_SCANNER
void grib_yyunput (int c,char *buf_ptr  );
void _grib_ignore_grib_yyunput_unused_error() { grib_yyunput(0,0); }
#endif
#endif
*/

#line 1131 "lex.grib_yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int grib_yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int grib_yylex_destroy (void );

int grib_yyget_debug (void );

void grib_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE grib_yyget_extra (void );

void grib_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *grib_yyget_in (void );

void grib_yyset_in  (FILE * in_str  );

FILE *grib_yyget_out (void );

void grib_yyset_out  (FILE * out_str  );

int grib_yyget_leng (void );

char *grib_yyget_text (void );

int grib_yyget_lineno (void );

void grib_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int grib_yywrap (void );
#else
extern int grib_yywrap (void );
#endif
#endif

    void grib_yyunput (int c,char *buf_ptr  );
    
#ifndef grib_yytext_ptr
static void grib_yy_flex_strncpy (char *,grib_yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int grib_yy_flex_strlen (grib_yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int grib_yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( grib_yytext, grib_yyleng, 1, grib_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( grib_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( grib_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, grib_yyin))==0 && ferror(grib_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(grib_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "grib_yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef grib_yyterminate
#define grib_yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) grib_yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int grib_yylex (void);

#define YY_DECL int grib_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after grib_yytext and grib_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register grib_yy_state_type grib_yy_current_state;
	register char *grib_yy_cp, *grib_yy_bp;
	register int grib_yy_act;
    
#line 57 "gribl.l"



#line 1317 "lex.grib_yy.c"

	if ( !(grib_yy_init) )
		{
		(grib_yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (grib_yy_start) )
			(grib_yy_start) = 1;	/* first start state */

		if ( ! grib_yyin )
			grib_yyin = stdin;

		if ( ! grib_yyout )
			grib_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			grib_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE );
		}

		grib_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		grib_yy_cp = (grib_yy_c_buf_p);

		/* Support of grib_yytext. */
		*grib_yy_cp = (grib_yy_hold_char);

		/* grib_yy_bp points to the position in grib_yy_ch_buf of the start of
		 * the current run.
		 */
		grib_yy_bp = grib_yy_cp;

		grib_yy_current_state = (grib_yy_start);
grib_yy_match:
		do
			{
			register YY_CHAR grib_yy_c = grib_yy_ec[YY_SC_TO_UI(*grib_yy_cp)];
			if ( grib_yy_accept[grib_yy_current_state] )
				{
				(grib_yy_last_accepting_state) = grib_yy_current_state;
				(grib_yy_last_accepting_cpos) = grib_yy_cp;
				}
			while ( grib_yy_chk[grib_yy_base[grib_yy_current_state] + grib_yy_c] != grib_yy_current_state )
				{
				grib_yy_current_state = (int) grib_yy_def[grib_yy_current_state];
				if ( grib_yy_current_state >= 517 )
					grib_yy_c = grib_yy_meta[(unsigned int) grib_yy_c];
				}
			grib_yy_current_state = grib_yy_nxt[grib_yy_base[grib_yy_current_state] + (unsigned int) grib_yy_c];
			++grib_yy_cp;
			}
		while ( grib_yy_base[grib_yy_current_state] != 2090 );

grib_yy_find_action:
		grib_yy_act = grib_yy_accept[grib_yy_current_state];
		if ( grib_yy_act == 0 )
			{ /* have to back up */
			grib_yy_cp = (grib_yy_last_accepting_cpos);
			grib_yy_current_state = (grib_yy_last_accepting_state);
			grib_yy_act = grib_yy_accept[grib_yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( grib_yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*grib_yy_cp = (grib_yy_hold_char);
			grib_yy_cp = (grib_yy_last_accepting_cpos);
			grib_yy_current_state = (grib_yy_last_accepting_state);
			goto grib_yy_find_action;

case 1:
YY_RULE_SETUP
#line 60 "gribl.l"
return EQ       ;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 61 "gribl.l"
return GE       ;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 62 "gribl.l"
return GT       ;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 63 "gribl.l"
return LE       ;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "gribl.l"
return LT       ;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 65 "gribl.l"
return NE       ;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 "gribl.l"
return NE       ;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 67 "gribl.l"
return BIT      ;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 "gribl.l"
return BITOFF   ;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "gribl.l"
return IS   ;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "gribl.l"
return NOT   ;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "gribl.l"
return NOT   ;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "gribl.l"
return AND   ;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "gribl.l"
return AND   ;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "gribl.l"
return OR   ;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "gribl.l"
return OR   ;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 78 "gribl.l"
return NIL   ;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 79 "gribl.l"
return DUMMY   ;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "gribl.l"
return LOWERCASE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "gribl.l"
return IF       ;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "gribl.l"
return IF_TRANSIENT       ;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "gribl.l"
return ELSE       ;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "gribl.l"
return UNSIGNED ;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "gribl.l"
return ASCII    ;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "gribl.l"
return BYTE    ;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "gribl.l"
return LABEL    ;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "gribl.l"
return LIST     ;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "gribl.l"
return WHILE     ;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "gribl.l"
return TEMPLATE ;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "gribl.l"
return TEMPLATE_NOFAIL ;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "gribl.l"
return TRIGGER ;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "gribl.l"
return END      ;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "gribl.l"
return IBMFLOAT ;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "gribl.l"
return FLOAT ;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "gribl.l"
return SIGNED   ;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "gribl.l"
return CODETABLE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "gribl.l"
return GETENV;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "gribl.l"
return CODETABLE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "gribl.l"
return FLAG     ;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "gribl.l"
return LOOKUP   ;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "gribl.l"
return META     ;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "gribl.l"
return PADTOEVEN    ;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "gribl.l"
return PADTO    ;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "gribl.l"
return PADTOMULTIPLE    ;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "gribl.l"
return PAD      ;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 "gribl.l"
return SECTION_PADDING      ;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 "gribl.l"
return MESSAGE      ;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "gribl.l"
return ALIAS    ;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "gribl.l"
return UNALIAS    ;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 "gribl.l"
return POS      ;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 "gribl.l"
return INTCONST ;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 "gribl.l"
return TRANS    ;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 115 "gribl.l"
return STRING_TYPE   ;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "gribl.l"
return LONG_TYPE   ;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "gribl.l"
return DOUBLE_TYPE   ;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "gribl.l"
return ITERATOR ;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 119 "gribl.l"
return NEAREST ;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 120 "gribl.l"
return BOX ;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 121 "gribl.l"
return KSEC    ;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 122 "gribl.l"
return FLAGBIT    ;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 123 "gribl.l"
return KSEC1EXPVER    ;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 124 "gribl.l"
return MODIFY    ;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 126 "gribl.l"
return G1_HALF_BYTE    ;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 127 "gribl.l"
return G1_MESSAGE_LENGTH    ;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 128 "gribl.l"
return G1_SECTION4_LENGTH    ;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 130 "gribl.l"
return EXPORT;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 131 "gribl.l"
return REMOVE;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 133 "gribl.l"
return SECTION_LENGTH     ;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 135 "gribl.l"
return ASSERT    ;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 137 "gribl.l"
return READ_ONLY;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 138 "gribl.l"
return NO_COPY;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 139 "gribl.l"
return EDITION_SPECIFIC;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 140 "gribl.l"
return DUMP;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 141 "gribl.l"
return NO_FAIL;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 142 "gribl.l"
return HIDDEN;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 143 "gribl.l"
return CAN_BE_MISSING;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 144 "gribl.l"
return MISSING;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 145 "gribl.l"
return CONSTRAINT;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 146 "gribl.l"
return OVERRIDE;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 147 "gribl.l"
return COPY_OK;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 149 "gribl.l"
return SET;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 150 "gribl.l"
return SET_NOFAIL;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 151 "gribl.l"
return WHEN;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 152 "gribl.l"
return CASE;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 153 "gribl.l"
return SWITCH;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 154 "gribl.l"
return DEFAULT;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 155 "gribl.l"
return CONCEPT;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 156 "gribl.l"
return CONCEPT_NOFAIL;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 157 "gribl.l"
return WRITE;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 158 "gribl.l"
return APPEND;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 159 "gribl.l"
return PRINT;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 160 "gribl.l"
return SKIP;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 162 "gribl.l"
{
          int c,q;
          while((c = input()) && isspace(c) && c != '\n') ;
          q = c; /* the quote */

          grib_yyleng = 0;
          while((c = input()) && c != q && c != '\n')
                {
                    if(c == '\\') grib_yytext[grib_yyleng++] = input();
                    else grib_yytext[grib_yyleng++] =  c;
                }

                grib_yytext[grib_yyleng++] = 0;

          grib_parser_include(grib_yytext);
         }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 179 "gribl.l"
{
           int c,q = grib_yytext[0];

           grib_yyleng = 0;

           while((c = input()) && c != q && c != '\n')
           {
               if(c == '\\') grib_yytext[grib_yyleng++] = input();
               else grib_yytext[grib_yyleng++] =  c;
            }

            grib_yytext[grib_yyleng++] = 0;
            grib_yylval.str = strdup(grib_yytext);
            return STRING;
        }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 195 "gribl.l"
{
           int c;
           unsigned long val = 0;

           while((c = input()) && c != '`' && c != '\n')
           {
                val <<= 8;
                val |= c;
           }
           grib_yylval.lval = val;
           return INTEGER;
        }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 209 "gribl.l"
{ grib_yylval.str = strdup(grib_yytext); return IDENT; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 210 "gribl.l"
{ grib_yylval.lval = atol((const char *)grib_yytext); return INTEGER; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 211 "gribl.l"
{ grib_yylval.dval = atof((const char *)grib_yytext); return FLOAT; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 214 "gribl.l"
{
           int c;
           while((c = input()) && (c != '\n')){}

        grib_yylineno++;
        }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 220 "gribl.l"
;
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 221 "gribl.l"
grib_yylineno++;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 225 "gribl.l"
return *grib_yytext;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 227 "gribl.l"
ECHO;
	YY_BREAK
#line 1961 "lex.grib_yy.c"
case YY_STATE_EOF(INITIAL):
	grib_yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int grib_yy_amount_of_matched_text = (int) (grib_yy_cp - (grib_yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*grib_yy_cp = (grib_yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed grib_yyin at a new source and called
			 * grib_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(grib_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->grib_yy_input_file = grib_yyin;
			YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for grib_yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since grib_yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (grib_yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)] )
			{ /* This was really a NUL. */
			grib_yy_state_type grib_yy_next_state;

			(grib_yy_c_buf_p) = (grib_yytext_ptr) + grib_yy_amount_of_matched_text;

			grib_yy_current_state = grib_yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * grib_yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			grib_yy_next_state = grib_yy_try_NUL_trans( grib_yy_current_state );

			grib_yy_bp = (grib_yytext_ptr) + YY_MORE_ADJ;

			if ( grib_yy_next_state )
				{
				/* Consume the NUL. */
				grib_yy_cp = ++(grib_yy_c_buf_p);
				grib_yy_current_state = grib_yy_next_state;
				goto grib_yy_match;
				}

			else
				{
				grib_yy_cp = (grib_yy_c_buf_p);
				goto grib_yy_find_action;
				}
			}

		else switch ( grib_yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(grib_yy_did_buffer_switch_on_eof) = 0;

				if ( grib_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * grib_yy_get_next_buffer() to have set up
					 * grib_yytext, we can now set up
					 * grib_yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(grib_yy_c_buf_p) = (grib_yytext_ptr) + YY_MORE_ADJ;

					grib_yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (grib_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(grib_yy_c_buf_p) =
					(grib_yytext_ptr) + grib_yy_amount_of_matched_text;

				grib_yy_current_state = grib_yy_get_previous_state(  );

				grib_yy_cp = (grib_yy_c_buf_p);
				grib_yy_bp = (grib_yytext_ptr) + YY_MORE_ADJ;
				goto grib_yy_match;

			case EOB_ACT_LAST_MATCH:
				(grib_yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)];

				grib_yy_current_state = grib_yy_get_previous_state(  );

				grib_yy_cp = (grib_yy_c_buf_p);
				grib_yy_bp = (grib_yytext_ptr) + YY_MORE_ADJ;
				goto grib_yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of grib_yylex */

/* grib_yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int grib_yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf;
	register char *source = (grib_yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (grib_yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (grib_yy_c_buf_p) - (grib_yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((grib_yy_c_buf_p) - (grib_yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int grib_yy_c_buf_p_offset =
				(int) ((grib_yy_c_buf_p) - b->grib_yy_ch_buf);

			if ( b->grib_yy_is_our_buffer )
				{
				int new_size = b->grib_yy_buf_size * 2;

				if ( new_size <= 0 )
					b->grib_yy_buf_size += b->grib_yy_buf_size / 8;
				else
					b->grib_yy_buf_size *= 2;

				b->grib_yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					grib_yyrealloc((void *) b->grib_yy_ch_buf,b->grib_yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->grib_yy_ch_buf = 0;

			if ( ! b->grib_yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(grib_yy_c_buf_p) = &b->grib_yy_ch_buf[grib_yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[number_to_move]),
			(grib_yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars);
		}

	if ( (grib_yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			grib_yyrestart(grib_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((grib_yy_size_t) ((grib_yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		grib_yy_size_t new_size = (grib_yy_n_chars) + number_to_move + ((grib_yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf = (char *) grib_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in grib_yy_get_next_buffer()" );
	}

	(grib_yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(grib_yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[0];

	return ret_val;
}

/* grib_yy_get_previous_state - get the state just before the EOB char was reached */

    static grib_yy_state_type grib_yy_get_previous_state (void)
{
	register grib_yy_state_type grib_yy_current_state;
	register char *grib_yy_cp;
    
	grib_yy_current_state = (grib_yy_start);

	for ( grib_yy_cp = (grib_yytext_ptr) + YY_MORE_ADJ; grib_yy_cp < (grib_yy_c_buf_p); ++grib_yy_cp )
		{
		register YY_CHAR grib_yy_c = (*grib_yy_cp ? grib_yy_ec[YY_SC_TO_UI(*grib_yy_cp)] : 1);
		if ( grib_yy_accept[grib_yy_current_state] )
			{
			(grib_yy_last_accepting_state) = grib_yy_current_state;
			(grib_yy_last_accepting_cpos) = grib_yy_cp;
			}
		while ( grib_yy_chk[grib_yy_base[grib_yy_current_state] + grib_yy_c] != grib_yy_current_state )
			{
			grib_yy_current_state = (int) grib_yy_def[grib_yy_current_state];
			if ( grib_yy_current_state >= 517 )
				grib_yy_c = grib_yy_meta[(unsigned int) grib_yy_c];
			}
		grib_yy_current_state = grib_yy_nxt[grib_yy_base[grib_yy_current_state] + (unsigned int) grib_yy_c];
		}

	return grib_yy_current_state;
}

/* grib_yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = grib_yy_try_NUL_trans( current_state );
 */
    static grib_yy_state_type grib_yy_try_NUL_trans  (grib_yy_state_type grib_yy_current_state )
{
	register int grib_yy_is_jam;
    	register char *grib_yy_cp = (grib_yy_c_buf_p);

	register YY_CHAR grib_yy_c = 1;
	if ( grib_yy_accept[grib_yy_current_state] )
		{
		(grib_yy_last_accepting_state) = grib_yy_current_state;
		(grib_yy_last_accepting_cpos) = grib_yy_cp;
		}
	while ( grib_yy_chk[grib_yy_base[grib_yy_current_state] + grib_yy_c] != grib_yy_current_state )
		{
		grib_yy_current_state = (int) grib_yy_def[grib_yy_current_state];
		if ( grib_yy_current_state >= 517 )
			grib_yy_c = grib_yy_meta[(unsigned int) grib_yy_c];
		}
	grib_yy_current_state = grib_yy_nxt[grib_yy_base[grib_yy_current_state] + (unsigned int) grib_yy_c];
	grib_yy_is_jam = (grib_yy_current_state == 516);

	return grib_yy_is_jam ? 0 : grib_yy_current_state;
}

    void grib_yyunput (int c, register char * grib_yy_bp )
{
	register char *grib_yy_cp;
    
    grib_yy_cp = (grib_yy_c_buf_p);

	/* undo effects of setting up grib_yytext */
	*grib_yy_cp = (grib_yy_hold_char);

	if ( grib_yy_cp < YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (grib_yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf )
			*--dest = *--source;

		grib_yy_cp += (int) (dest - source);
		grib_yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars =
			(grib_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size;

		if ( grib_yy_cp < YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--grib_yy_cp = (char) c;

	(grib_yytext_ptr) = grib_yy_bp;
	(grib_yy_hold_char) = *grib_yy_cp;
	(grib_yy_c_buf_p) = grib_yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int grib_yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(grib_yy_c_buf_p) = (grib_yy_hold_char);

	if ( *(grib_yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* grib_yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (grib_yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)] )
			/* This was really a NUL. */
			*(grib_yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (grib_yy_c_buf_p) - (grib_yytext_ptr);
			++(grib_yy_c_buf_p);

			switch ( grib_yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because grib_yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					grib_yyrestart(grib_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( grib_yywrap( ) )
						return EOF;

					if ( ! (grib_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return grib_yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(grib_yy_c_buf_p) = (grib_yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (grib_yy_c_buf_p);	/* cast for 8-bit char's */
	*(grib_yy_c_buf_p) = '\0';	/* preserve grib_yytext */
	(grib_yy_hold_char) = *++(grib_yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void grib_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        grib_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE );
	}

	grib_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	grib_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void grib_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		grib_yypop_buffer_state();
	 *		grib_yypush_buffer_state(new_buffer);
     */
	grib_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(grib_yy_c_buf_p) = (grib_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_pos = (grib_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	grib_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (grib_yywrap()) processing, but the only time this flag
	 * is looked at is after grib_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(grib_yy_did_buffer_switch_on_eof) = 1;
}

static void grib_yy_load_buffer_state  (void)
{
    	(grib_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars;
	(grib_yytext_ptr) = (grib_yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_pos;
	grib_yyin = YY_CURRENT_BUFFER_LVALUE->grib_yy_input_file;
	(grib_yy_hold_char) = *(grib_yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE grib_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) grib_yyalloc(sizeof( struct grib_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_create_buffer()" );

	b->grib_yy_buf_size = size;

	/* grib_yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->grib_yy_ch_buf = (char *) grib_yyalloc(b->grib_yy_buf_size + 2  );
	if ( ! b->grib_yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_create_buffer()" );

	b->grib_yy_is_our_buffer = 1;

	grib_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with grib_yy_create_buffer()
 * 
 */
    void grib_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->grib_yy_is_our_buffer )
		grib_yyfree((void *) b->grib_yy_ch_buf  );

	grib_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a grib_yyrestart() or at EOF.
 */
    static void grib_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	grib_yy_flush_buffer(b );

	b->grib_yy_input_file = file;
	b->grib_yy_fill_buffer = 1;

    /* If b is the current buffer, then grib_yy_init_buffer was _probably_
     * called from grib_yyrestart() or through grib_yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->grib_yy_bs_lineno = 1;
        b->grib_yy_bs_column = 0;
    }

        b->grib_yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void grib_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->grib_yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->grib_yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->grib_yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->grib_yy_buf_pos = &b->grib_yy_ch_buf[0];

	b->grib_yy_at_bol = 1;
	b->grib_yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		grib_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void grib_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	grib_yyensure_buffer_stack();

	/* This block is copied from grib_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(grib_yy_c_buf_p) = (grib_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_pos = (grib_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(grib_yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from grib_yy_switch_to_buffer. */
	grib_yy_load_buffer_state( );
	(grib_yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void grib_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	grib_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((grib_yy_buffer_stack_top) > 0)
		--(grib_yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		grib_yy_load_buffer_state( );
		(grib_yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void grib_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(grib_yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(grib_yy_buffer_stack) = (struct grib_yy_buffer_state**)grib_yyalloc
								(num_to_alloc * sizeof(struct grib_yy_buffer_state*)
								);
		if ( ! (grib_yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in grib_yyensure_buffer_stack()" );
								  
		memset((grib_yy_buffer_stack), 0, num_to_alloc * sizeof(struct grib_yy_buffer_state*));
				
		(grib_yy_buffer_stack_max) = num_to_alloc;
		(grib_yy_buffer_stack_top) = 0;
		return;
	}

	if ((grib_yy_buffer_stack_top) >= ((grib_yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (grib_yy_buffer_stack_max) + grow_size;
		(grib_yy_buffer_stack) = (struct grib_yy_buffer_state**)grib_yyrealloc
								((grib_yy_buffer_stack),
								num_to_alloc * sizeof(struct grib_yy_buffer_state*)
								);
		if ( ! (grib_yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in grib_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((grib_yy_buffer_stack) + (grib_yy_buffer_stack_max), 0, grow_size * sizeof(struct grib_yy_buffer_state*));
		(grib_yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE grib_yy_scan_buffer  (char * base, grib_yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) grib_yyalloc(sizeof( struct grib_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_scan_buffer()" );

	b->grib_yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->grib_yy_buf_pos = b->grib_yy_ch_buf = base;
	b->grib_yy_is_our_buffer = 0;
	b->grib_yy_input_file = 0;
	b->grib_yy_n_chars = b->grib_yy_buf_size;
	b->grib_yy_is_interactive = 0;
	b->grib_yy_at_bol = 1;
	b->grib_yy_fill_buffer = 0;
	b->grib_yy_buffer_status = YY_BUFFER_NEW;

	grib_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to grib_yylex() will
 * scan from a @e copy of @a str.
 * @param grib_yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       grib_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE grib_yy_scan_string (grib_yyconst char * grib_yystr )
{
    
	return grib_yy_scan_bytes(grib_yystr,strlen(grib_yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to grib_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE grib_yy_scan_bytes  (grib_yyconst char * grib_yybytes, int  _grib_yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	grib_yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _grib_yybytes_len + 2;
	buf = (char *) grib_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_scan_bytes()" );

	for ( i = 0; i < _grib_yybytes_len; ++i )
		buf[i] = grib_yybytes[i];

	buf[_grib_yybytes_len] = buf[_grib_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = grib_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in grib_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->grib_yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void grib_yy_fatal_error (grib_yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine grib_yyless() so it works in section 3 code. */

#undef grib_yyless
#define grib_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up grib_yytext. */ \
        int grib_yyless_macro_arg = (n); \
        YY_LESS_LINENO(grib_yyless_macro_arg);\
		grib_yytext[grib_yyleng] = (grib_yy_hold_char); \
		(grib_yy_c_buf_p) = grib_yytext + grib_yyless_macro_arg; \
		(grib_yy_hold_char) = *(grib_yy_c_buf_p); \
		*(grib_yy_c_buf_p) = '\0'; \
		grib_yyleng = grib_yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int grib_yyget_lineno  (void)
{
        
    return grib_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *grib_yyget_in  (void)
{
        return grib_yyin;
}

/** Get the output stream.
 * 
 */
FILE *grib_yyget_out  (void)
{
        return grib_yyout;
}

/** Get the length of the current token.
 * 
 */
int grib_yyget_leng  (void)
{
        return grib_yyleng;
}

/** Get the current token.
 * 
 */

char *grib_yyget_text  (void)
{
        return grib_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void grib_yyset_lineno (int  line_number )
{
    
    grib_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see grib_yy_switch_to_buffer
 */
void grib_yyset_in (FILE *  in_str )
{
        grib_yyin = in_str ;
}

void grib_yyset_out (FILE *  out_str )
{
        grib_yyout = out_str ;
}

int grib_yyget_debug  (void)
{
        return grib_yy_flex_debug;
}

void grib_yyset_debug (int  bdebug )
{
        grib_yy_flex_debug = bdebug ;
}

static int grib_yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from grib_yylex_destroy(), so don't allocate here.
     */

    (grib_yy_buffer_stack) = 0;
    (grib_yy_buffer_stack_top) = 0;
    (grib_yy_buffer_stack_max) = 0;
    (grib_yy_c_buf_p) = (char *) 0;
    (grib_yy_init) = 0;
    (grib_yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    grib_yyin = stdin;
    grib_yyout = stdout;
#else
    grib_yyin = (FILE *) 0;
    grib_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * grib_yylex_init()
     */
    return 0;
}

/* grib_yylex_destroy is for both reentrant and non-reentrant scanners. */
int grib_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		grib_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		grib_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	grib_yyfree((grib_yy_buffer_stack) );
	(grib_yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * grib_yylex() is called, initialization will occur. */
    grib_yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef grib_yytext_ptr
static void grib_yy_flex_strncpy (char* s1, grib_yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int grib_yy_flex_strlen (grib_yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *grib_yyalloc (grib_yy_size_t  size )
{
	return (void *) malloc( size );
}

void *grib_yyrealloc  (void * ptr, grib_yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void grib_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see grib_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "grib_yytables"

#line 227 "gribl.l"




