/*
 * (C) Copyright 2005- ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * In applying this licence, ECMWF does not waive the privileges and immunities granted to it by
 * virtue of its status as an intergovernmental organisation nor does it submit to any jurisdiction.
 */

#include "grib_api_internal.h"

/* This file is generated by ./make_class.pl */
#include "dumper/grib_dumper.h"


struct table_entry
{
    const char* type;
};


static struct table_entry table[] = {
    { "bufr_decode_C", &grib_dumper_class_bufr_decode_C, },
    { "bufr_decode_filter", &grib_dumper_class_bufr_decode_filter, },
    { "bufr_decode_fortran", &grib_dumper_class_bufr_decode_fortran, },
    { "bufr_decode_python", &grib_dumper_class_bufr_decode_python, },
    { "bufr_encode_C", &grib_dumper_class_bufr_encode_C, },
    { "bufr_encode_filter", &grib_dumper_class_bufr_encode_filter, },
    { "bufr_encode_fortran", &grib_dumper_class_bufr_encode_fortran, },
    { "bufr_encode_python", &grib_dumper_class_bufr_encode_python, },
    { "bufr_simple", &grib_dumper_class_bufr_simple, },
    { "debug", &grib_dumper_class_debug, },
    { "default", &grib_dumper_class_default, },
    { "grib_encode_C", &grib_dumper_class_grib_encode_C, },
    { "json", &grib_dumper_class_json, },
    { "serialize", &grib_dumper_class_serialize, },
    { "wmo", &grib_dumper_class_wmo, },
};

eccodes::Dumper* grib_dumper_factory(const char* op, const grib_handle* h, FILE* out, unsigned long option_flags, void* arg)
{
    size_t i                       = 0;
    const size_t num_table_entries = sizeof(table) / sizeof(table[0]);
    for (i = 0; i < num_table_entries; i++)
        if (strcmp(op, table[i].type) == 0) {
            grib_dumper_class* c = *(table[i].cclass);
            grib_dumper* d       = (grib_dumper*)grib_context_malloc_clear(h->context, c->size);
            d->depth             = 0;
            d->context           = h->context;
            d->cclass            = c;
            d->option_flags      = option_flags;
            d->arg               = arg;
            d->out               = out;
            grib_init_dumper(d);
            grib_context_log(h->context, GRIB_LOG_DEBUG, "Creating dumper of type : %s ", op);
            return d;
        }
    grib_context_log(h->context, GRIB_LOG_ERROR, "Unknown type : '%s' for dumper", op);
    return NULL;
}

