/* This file is automatically generated by ./make_class.pl, do not edit */
{ "c_code", &grib_dumper_class_c_code, },
{ "debug", &grib_dumper_class_debug, },
{ "default", &grib_dumper_class_default, },
{ "keys", &grib_dumper_class_keys, },
{ "serialize", &grib_dumper_class_serialize, },
{ "wmo", &grib_dumper_class_wmo, },
