/*
 * Copyright 2005-2018 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * In applying this licence, ECMWF does not waive the privileges and immunities granted to it by
 * virtue of its status as an intergovernmental organisation nor does it submit to any jurisdiction.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jgribapi_GribIterator */

#ifndef _Included_jgribapi_GribIterator
#define _Included_jgribapi_GribIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jgribapi_GribIterator
 * Method:    gribIteratorGetNext
 * Signature: (J)Ljgribapi/GribPoint;
 */
JNIEXPORT jobject JNICALL Java_jgribapi_GribIterator_gribIteratorGetNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jgribapi_GribIterator
 * Method:    gribIteratorHasNext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jgribapi_GribIterator_gribIteratorHasNext
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
