name: cd

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - '*'

jobs:
  # wheel:
  #   uses: ./.github/workflows/build-wheel-wrapper.yml
  #   secrets: inherit    
  tarball:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-tarball.yml@v2
    secrets: inherit
    with:
      confluence_space: ${{ vars.TARBALL_CONFLUENCE_SPACE }}
  conda:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-conda.yml@cd-conda-multi-platform
    secrets: inherit
    with:
      platforms: |
        linux-64
        linux-aarch64
        osx-arm64
  system-package:
    strategy:
      fail-fast: false
      matrix:
        os: [debian-11, debian-12, debian-13, rocky-8, rocky-9, rocky-10]
    uses: ecmwf/reusable-workflows/.github/workflows/cd-system-package.yml@v2
    secrets: inherit
    with:
      os: ${{ matrix.os }}
      dependencies: |
        ecmwf/ecbuild
        MathisRosenhauer/libaec@refs/tags/v1.1.4
      dependency_branch: develop

