name: cd

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    uses: ecmwf/reusable-workflows/.github/workflows/create-package.yml@v2
    secrets: inherit
  wheel:
    uses: ./.github/workflows/build-wheel-wrapper.yml
    secrets: inherit    
  tarball:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-tarball.yml@v2
    secrets: inherit
    with:
      confluence_space: ${{ vars.TARBALL_CONFLUENCE_SPACE }}
  conda:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-conda.yml@v2
    secrets: inherit      
