name: nightly

on:
  workflow_dispatch: ~

  # Run at 20:00 UTC every day (on default branch)
  schedule:
    - cron: "0 20 * * *"

jobs:
  test:
    uses: ./.github/workflows/reusable-ci-hpc.yml
    with:
      eccodes: ecmwf/eccodes@${{ github.event.pull_request.head.sha || github.sha }}
      nightly_test: true
    secrets: inherit

  notify:
    runs-on: ubuntu-latest
    needs:
      - test
    if: always()
    steps:
      - name: Trigger Teams notification
        uses: ecmwf-actions/notify-teams@v1
        with:
          incoming_webhook: ${{ secrets.MS_TEAMS_INCOMING_WEBHOOK }}
          needs_context: ${{ toJSON(needs) }}
          workflow_id: nightly.yml
