name: Notify new PR

on:
  pull_request_target:
    types:
      - "opened"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify new PR
        uses: ecmwf-actions/notify-teams-pr@v1
        with:
          incoming_webhook: ${{ secrets.MS_TEAMS_INCOMING_WEBHOOK }}
