name: reusable-ci

on:
  workflow_call:
    inputs:
      eccodes:
        required: false
        type: string

jobs:
  ci:
    name: eccodes-ci
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci.yml@v2
    with:
      repository: ${{ inputs.eccodes || 'ecmwf/eccodes@develop' }}
      name_prefix: eccodes-
      build_package_inputs: |
        repository: ${{ inputs.eccodes || 'ecmwf/eccodes@develop' }}
        self_coverage: true
        dependencies: |
          ecmwf/ecbuild
          MathisRosenhauer/libaec@master
        dependency_branch: develop
        parallelism_factor: 8
    secrets: inherit
